/* GENERATED by abi/gen_bindings.py. Do not edit. */
/* =====================================================================
 * CXGEOS ABI version 1 -- 35 slots
 * =====================================================================
 * Call the kernel through these addresses. This header links nothing:
 * the kernel is already in memory when your app runs.
 *
 * CXGEOS passes arguments in the parameter block at $22 -- X16_P0..P7,
 * the same block x16lib uses -- because the kernel is assembly and a
 * fixed block is the one convention all five C compilers can agree on.
 * Set cx_p[] and call the slot:
 *
 *     cx_p[0] = 100; cx_p[1] = 0;      -- x = 100
 *     cx_p[2] = 50;  cx_p[3] = 0;      -- y = 50
 *     cx_call(CX_DIRTY_ADD);           -- args all in cx_p
 *
 * Only the bare cx_call is defined here so far: slots that take a
 * byte in A or a pointer in A/X need this compiler's own argument
 * conventions honoured, and a guessed macro that quietly puts the
 * byte in the wrong place is worse than none. The llvm header shows
 * the finished shape; x16_clib's ABI table is the reference for the
 * conventions. The helpers land per compiler, tested, with the SDK
 * packaging phase.
 * ===================================================================== */

#ifndef CXGEOS_H
#define CXGEOS_H

#define CX_ABI_VERSION  1
#define CX_ABI_SLOTS    35

/* the parameter block: X16_P0..P7 */
#define cx_p            ((volatile unsigned char *)0x0022)


/* --- system --- */
#define CX_VERSION         0x8010   /* -> A/X = ABI version */
#define CX_EXIT            0x8013   /* never returns: back to the shell */

/* --- screen (gfx2, 640x480 @2bpp) --- */
#define CX_GFX_INIT        0x8016   /* - */
#define CX_GFX_CLEAR       0x8019   /* A = colour 0-3 */
#define CX_GFX_PSET        0x801C   /* P0/P1 = x, P2/P3 = y, A = colour (clipped) */
#define CX_GFX_READ        0x801F   /* P0/P1 = x, P2/P3 = y -> A = colour, $FF off screen */
#define CX_GFX_HLINE       0x8022   /* P0/P1 = x, P2/P3 = y, P4/P5 = len, A = colour */
#define CX_GFX_VLINE       0x8025   /* P0/P1 = x, P2/P3 = y, P4/P5 = len, A = colour */
#define CX_GFX_RECT        0x8028   /* P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h, A = colour */
#define CX_GFX_FRAME       0x802B   /* P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h, A = colour */
#define CX_GFX_LINE        0x802E   /* P0/P1 = x0, P2/P3 = y0, P4/P5 = x1, P6/P7 = y1, A = colour */
#define CX_GFX_PATTERN     0x8031   /* A/X = 8x8 pattern, Y = (bg << 2) | fg */
#define CX_GFX_PATRECT     0x8034   /* P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h */
#define CX_GFX_BLIT        0x8037   /* P0/P1 = x, P2/P3 = y, P4 = wbytes, P5 = h, P6/P7 = src, A = op */
#define CX_GFX_BLITM       0x803A   /* P0/P1 = x, P2/P3 = y, P4 = h, P5 = cols, P6/P7 = src */

/* --- text --- */
#define CX_FONT_SET        0x803D   /* A/X = CXF image -> carry set if bad */
#define CX_FONT_STYLE      0x8040   /* A = CX_BOLD | CX_UNDER */
#define CX_FONT_MEASURE    0x8043   /* A/X = string -> P0/P1 = width */
#define CX_FONT_DRAW       0x8046   /* P0/P1 = x, P2/P3 = y, A/X = string -> P0/P1 = pen */

/* --- events --- */
#define CX_EV_HANDLERS     0x8049   /* A/X = a table of CX_EV_COUNT vectors */
#define CX_EV_MAINLOOP     0x804C   /* never returns */
#define CX_EV_DISPATCH     0x804F   /* dispatch one event and return */
#define CX_EV_GET          0x8052   /* -> P0..P7 = a record; carry set if none */
#define CX_EV_POST         0x8055   /* P0..P7 = a record */
#define CX_EV_COUNT        0x8058   /* -> A = records waiting */
#define CX_EV_TIMER        0x805B   /* A = frames between EV_TIMERs (0 = off) */
#define CX_EV_FRAMES       0x805E   /* -> A = the frame counter */

/* --- dirty rectangles --- */
#define CX_DIRTY_RESET     0x8061   /* - */
#define CX_DIRTY_ADD       0x8064   /* P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h */
#define CX_DIRTY_COUNT     0x8067   /* -> A = rects */
#define CX_DIRTY_GET       0x806A   /* A = index -> P0/P1 = x0, P2/P3 = y0, P4/P5 = x1, P6/P7 = y1 */

/* --- the loader --- */
#define CX_APP_LOAD        0x806D   /* A/X = filename, Y = length; returns only on failure: carry, A = 1 not an app / 2 needs a newer kernel */

/* --- events, continued --- */
#define CX_EV_INIT         0x8070   /* clear the queue and hook the raster; an app calls this before cx_ev_handlers */

/* --- menus --- */
#define CX_MENU_SET        0x8073   /* A/X = the menu bar (docs/formats.md); draws it, owns the top strip; carry = region stack full */
#define CX_MENU_OFF        0x8076   /* forget the menu; only with no menu open */

/* A bare call: every argument already sits in cx_p. */
#define cx_call(slot)      ((*(void (*)(void))(slot))())

#endif /* CXGEOS_H */
