#!/usr/bin/env python3
"""gen_cover.py -- (re)generate test/asmsdk_cover.asm.

A coverage stub that invokes every cxm_ macro once, so the asmsdk fidelity
gate (build.ps1 -Test) can diff the spec-generated ca65 layer against the
hand-written one over ALL macros, not just those a real app happens to use.
The stub assembles; it is not meant to run.

    python test/gen_cover.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "abi"))
import asmsdk

L = [
    "; ca65 -- GENERATED by test/gen_cover.py. Do not edit.",
    "; Invokes every cxm_ macro once so the asmsdk fidelity gate covers them",
    "; all (hand-written asmsdk/ca65 vs the spec-generated one, byte-identical",
    "; machine code). Assembles; not meant to run.",
    '.include "x16.asm"',
    '.include "asmsdk/ca65/cxgeos.inc"',
    '.segment "LOADADDR"',
    "    .word $0801",
    '.segment "CODE"',
    "    basic_stub",
    "cover_calls:",
]
for spec in asmsdk.CALLS:
    name, params = spec[0], spec[1]
    args = ", ".join("1" for _ in params)
    L.append("    cxm_%s%s" % (name, (" " + args) if args else ""))
for name, params, body, cm in asmsdk.ALIASES:
    args = ", ".join("1" for _ in params)
    L.append("    cxm_%s%s" % (name, (" " + args) if args else ""))
L.append("    rts")
L.append("")
L.append("cover_data:")
for spec in asmsdk.BUILDERS:
    name, params = spec[0], spec[1]
    if name == "wcount":
        L += ["cover_wc_a:", "    cxm_wcount cover_wc_a, cover_wc_b", "cover_wc_b:"]
        continue
    args = ", ".join("1" for _ in params)
    L.append("    cxm_%s%s" % (name, (" " + args) if args else ""))

(ROOT / "test" / "asmsdk_cover.asm").write_text("\n".join(L) + "\n", encoding="ascii", newline="\n")
print("wrote test/asmsdk_cover.asm (%d calls + %d aliases + %d builders)"
      % (len(asmsdk.CALLS), len(asmsdk.ALIASES), len(asmsdk.BUILDERS)))
