/* GENERATED by abi/gen_bindings.py. Do not edit. */
/* =====================================================================
 * CXGEOS ABI version 1 -- 52 slots
 * =====================================================================
 * Call the kernel through these addresses. This header links nothing:
 * the kernel is already in memory when your app runs.
 *
 * CXGEOS passes arguments in the parameter block at $22 -- X16_P0..P7,
 * the same block x16lib uses -- because the kernel is assembly and a
 * fixed block is the one convention all five C compilers can agree on.
 * Set cx_p[] and call the slot:
 *
 *     cx_p[0] = 100; cx_p[1] = 0;      -- x = 100
 *     cx_p[2] = 50;  cx_p[3] = 0;      -- y = 50
 *     cx_call_a(CX_GFX_PSET, 3);       -- colour 3
 *
 * On THIS compiler, cx_p is not the block itself. llvm-mos keeps its
 * soft stack pointer (__rc0/__rc1) and two reserved registers at
 * $22-$25 -- the same bytes as the kernel's block -- so a C write to
 * $22 corrupts the compiler's own stack. cx_p here is a mirror in
 * ordinary memory, and cx_run() carries it across the real block,
 * saving $22-$25 around the call. The mirror also carries what a
 * 6502 call has that C cannot see: cx_a/cx_x/cx_y go in; cx_a, cx_x
 * and cx_c -- the carry -- come back, so cx_ev_get can be judged.
 *
 * Build with -mreserve-zp=90: clang's whole-program pass otherwise
 * claims zero page from $26 up for hot statics, and everything from
 * $26 to $7F belongs to the kernel or to the app ZP convention.
 * ===================================================================== */

#ifndef CXGEOS_H
#define CXGEOS_H

#define CX_ABI_VERSION  1
#define CX_ABI_SLOTS    52

/* the parameter block's mirror -- see the note above; the real block
 * at $22 is touched only inside cx_run(). Weak, so every translation
 * unit shares one copy under one unmangled name the asm can see. */
/* `used` keeps LTO from discarding what only the asm reads */
__attribute__((weak, used)) volatile unsigned char cx_p[8];
__attribute__((weak, used)) volatile unsigned char cx_a, cx_x, cx_y, cx_c;
__attribute__((weak, used)) volatile unsigned int  cx_slot;


/* --- system --- */
#define CX_VERSION         0x8010   /* -> A/X = ABI version */
#define CX_EXIT            0x8013   /* never returns: back to the shell */

/* --- screen (gfx2, 640x480 @2bpp) --- */
#define CX_GFX_INIT        0x8016   /* - */
#define CX_GFX_CLEAR       0x8019   /* A = colour 0-3 */
#define CX_GFX_PSET        0x801C   /* P0/P1 = x, P2/P3 = y, A = colour (clipped) */
#define CX_GFX_READ        0x801F   /* P0/P1 = x, P2/P3 = y -> A = colour, $FF off screen */
#define CX_GFX_HLINE       0x8022   /* P0/P1 = x, P2/P3 = y, P4/P5 = len, A = colour */
#define CX_GFX_VLINE       0x8025   /* P0/P1 = x, P2/P3 = y, P4/P5 = len, A = colour */
#define CX_GFX_RECT        0x8028   /* P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h, A = colour */
#define CX_GFX_FRAME       0x802B   /* P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h, A = colour */
#define CX_GFX_LINE        0x802E   /* P0/P1 = x0, P2/P3 = y0, P4/P5 = x1, P6/P7 = y1, A = colour */
#define CX_GFX_PATTERN     0x8031   /* A/X = 8x8 pattern, Y = (bg << 2) | fg */
#define CX_GFX_PATRECT     0x8034   /* P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h */
#define CX_GFX_BLIT        0x8037   /* P0/P1 = x, P2/P3 = y, P4 = wbytes, P5 = h, P6/P7 = src, A = op */
#define CX_GFX_BLITM       0x803A   /* P0/P1 = x, P2/P3 = y, P4 = h, P5 = cols, P6/P7 = src */

/* --- text --- */
#define CX_FONT_SET        0x803D   /* A/X = CXF image -> carry set if bad */
#define CX_FONT_STYLE      0x8040   /* A = CX_BOLD | CX_UNDER */
#define CX_FONT_MEASURE    0x8043   /* A/X = string -> P0/P1 = width */
#define CX_FONT_DRAW       0x8046   /* P0/P1 = x, P2/P3 = y, A/X = string -> P0/P1 = pen */

/* --- events --- */
#define CX_EV_HANDLERS     0x8049   /* A/X = a table of CX_EV_COUNT vectors */
#define CX_EV_MAINLOOP     0x804C   /* never returns */
#define CX_EV_DISPATCH     0x804F   /* dispatch one event and return */
#define CX_EV_GET          0x8052   /* -> P0..P7 = a record; carry set if none */
#define CX_EV_POST         0x8055   /* P0..P7 = a record */
#define CX_EV_COUNT        0x8058   /* -> A = records waiting */
#define CX_EV_TIMER        0x805B   /* A = frames between EV_TIMERs (0 = off) */
#define CX_EV_FRAMES       0x805E   /* -> A = the frame counter */

/* --- dirty rectangles --- */
#define CX_DIRTY_RESET     0x8061   /* - */
#define CX_DIRTY_ADD       0x8064   /* P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h */
#define CX_DIRTY_COUNT     0x8067   /* -> A = rects */
#define CX_DIRTY_GET       0x806A   /* A = index -> P0/P1 = x0, P2/P3 = y0, P4/P5 = x1, P6/P7 = y1 */

/* --- the loader --- */
#define CX_APP_LOAD        0x806D   /* A/X = filename, Y = length; returns only on failure: carry, A = 1 not an app / 2 needs a newer kernel */

/* --- events, continued --- */
#define CX_EV_INIT         0x8070   /* clear the queue and hook the raster; an app calls this before cx_ev_handlers */

/* --- menus --- */
#define CX_MENU_SET        0x8073   /* A/X = the menu bar (docs/formats.md); draws it, owns the top strip; carry = region stack full */
#define CX_MENU_OFF        0x8076   /* forget the menu; only with no menu open */

/* --- the pointer --- */
#define CX_MOUSE_SHOW      0x8079   /* A = the pointer number (1 = the arrow), or $FF to show without setting one; the loader hides it between apps, so an app that wants it asks */
#define CX_MOUSE_HIDE      0x807C   /* - */

/* --- themes and dialogs --- */
#define CX_THEME_SET       0x807F   /* A/X = a 12-byte theme record (docs/formats.md): four palette RGBs plus the role indices; the palette changes instantly */
#define CX_DLG_ALERT       0x8082   /* A/X = a dialog descriptor (docs/formats.md); SYNCHRONOUS -- returns A = the chosen button. RETURN picks button 0 */

/* --- widgets --- */
#define CX_WG_SET          0x8085   /* A/X = a widget list (docs/formats.md); draws it, routes its clicks; posts EV_WIDGET(detail = index, P2 = value) */
#define CX_WG_DRAW         0x8088   /* redraw the current widget list */

/* --- keyboard menu nav --- */
#define CX_MENU_KEY        0x808B   /* A = a key; drives the menu bar (DOWN opens, arrows move, RETURN picks, ESC dismisses). Carry set if it was a menu key; clobbers X and Y. Call it from your EV_KEY handler */

/* --- keyboard widget focus --- */
#define CX_WG_KEY          0x808E   /* A = a key; TAB/UP move focus, SPACE/RETURN activate, LEFT/RIGHT step a scrollbar, printable keys type into a focused field. Carry set if it was a widget key; clobbers X and Y. Call from EV_KEY */

/* --- the directory --- */
#define CX_DIR_OPEN        0x8091   /* A/X = a pattern like "$", Y = length; opens the directory channel. Carry set on a DOS error */
#define CX_DIR_NEXT        0x8094   /* P0/P1 = a >=17-byte buffer; fills the entry's name, A = 0 file / 1 dir. Carry set = listing done. The first entry is the volume header */
#define CX_DIR_CLOSE       0x8097   /* close the directory channel */

/* --- the DOS command channel --- */
#define CX_DOS_CMD         0x809A   /* A/X = a CMDR-DOS command ("S:F", "R:NEW=OLD", "MD:D", "CD:D"...), Y = length -> A = status code, carry set when it is an error (>= 20); the reply text waits for cx_dos_msg */
#define CX_DOS_MSG         0x809D   /* P0/P1 = a >=64-byte buffer; copies the last DOS reply ("62,FILE NOT FOUND,00,00"), NUL-terminated -> A = its length */

/* --- dialogs, continued --- */
#define CX_DLG_PROMPT      0x80A0   /* A/X = message, P0/P1 = a NUL-terminated buffer (may be seeded), P2 = its capacity; SYNCHRONOUS one-line editor with ok/cancel -> A = the length, carry set if cancelled. RETURN is ok, ESC is cancel */

/* --- the clipboard --- */
#define CX_CLIP_PUT        0x80A3   /* A = type (1 = TEXT; 0 or length 0 empties), P0/P1 = source, P2/P3 = length -> carry set if too big (~32KB fits) */
#define CX_CLIP_GET        0x80A6   /* P0/P1 = destination, P2/P3 = its capacity -> A = the type (0 = empty), P2/P3 = the length copied (what is held or what fits, whichever is less) */
#define CX_CLIP_TYPE       0x80A9   /* -> A = the type waiting (0 = empty), P2/P3 = its length; nothing is consumed */

/* The crossing itself. The slot address is parked in __rc2/3 before
 * anything moves; $22-$25 ride the hardware stack; the mirror is
 * copied in, A/X/Y loaded, the slot called through a trampoline, and
 * registers, carry and the block all copied back out. An event IRQ
 * landing mid-crossing is fine: the kernel's handler saves and
 * restores the whole $02-$31 range around itself. */
__attribute__((weak, noinline)) void cx_run(void) {
    asm volatile(
        "lda cx_slot\n\t"
        "sta __rc2\n\t"
        "lda cx_slot+1\n\t"
        "sta __rc3\n\t"
        "lda 0x22\n\tpha\n\t"
        "lda 0x23\n\tpha\n\t"
        "lda 0x24\n\tpha\n\t"
        "lda 0x25\n\tpha\n\t"
        "ldy #7\n\t"
        "1:\n\t"
        "lda cx_p,y\n\t"
        "sta 0x22,y\n\t"
        "dey\n\t"
        "bpl 1b\n\t"
        "ldy cx_y\n\t"
        "ldx cx_x\n\t"
        "lda cx_a\n\t"
        "jsr 2f\n\t"
        "sta cx_a\n\t"
        "stx cx_x\n\t"
        "php\n\t"
        "pla\n\t"
        "and #1\n\t"
        "sta cx_c\n\t"
        "ldy #7\n\t"
        "3:\n\t"
        "lda 0x22,y\n\t"
        "sta cx_p,y\n\t"
        "dey\n\t"
        "bpl 3b\n\t"
        "pla\n\tsta 0x25\n\t"
        "pla\n\tsta 0x24\n\t"
        "pla\n\tsta 0x23\n\t"
        "pla\n\tsta 0x22\n\t"
        "bra 4f\n\t"
        "2:\n\t"
        "jmp (__rc2)\n\t"
        "4:"
        ::: "a", "x", "y", "cc", "memory");
}

#define cx_call(slot)          (cx_slot = (slot), cx_run())
#define cx_call_a(slot, a)     (cx_a = (unsigned char)(a), cx_call(slot))
#define cx_call_ax(slot, a, x) (cx_a = (unsigned char)(a), cx_x = (unsigned char)(x), cx_call(slot))
#define cx_call_p(slot, ptr)   cx_call_ax((slot), ((unsigned int)(ptr)) & 0xFF, ((unsigned int)(ptr)) >> 8)
#define cx_ret(slot)           (cx_call(slot), cx_a)
#define cx_ret16(slot)         (cx_call(slot), (unsigned int)cx_a | ((unsigned int)cx_x << 8))

#endif /* CXGEOS_H */
