/* GENERATED by abi/gen_bindings.py. Do not edit. */
/* =====================================================================
 * CXGEOS ABI version 1 -- 85 slots
 * =====================================================================
 * Call the kernel through these addresses. This header links nothing:
 * the kernel is already in memory when your app runs.
 *
 * CXGEOS passes arguments in the parameter block at $22 -- X16_P0..P7,
 * the same block x16lib uses -- because the kernel is assembly and a
 * fixed block is the one convention all five C compilers can agree on.
 * Set cx_p[] and call the slot:
 *
 *     cx_p[0] = 100; cx_p[1] = 0;      -- x = 100
 *     cx_p[2] = 50;  cx_p[3] = 0;      -- y = 50
 *     cx_call_a(CX_GFX_PSET, 3);       -- colour 3
 *
 * On THIS compiler, cx_p is not the block itself. llvm-mos keeps its
 * soft stack pointer (__rc0/__rc1) and two reserved registers at
 * $22-$25 -- the same bytes as the kernel's block -- so a C write to
 * $22 corrupts the compiler's own stack. cx_p here is a mirror in
 * ordinary memory, and cx_run() carries it across the real block,
 * saving $22-$25 around the call. The mirror also carries what a
 * 6502 call has that C cannot see: cx_a/cx_x/cx_y go in; cx_a, cx_x
 * and cx_c -- the carry -- come back, so cx_ev_get can be judged.
 *
 * Build with -mreserve-zp=90: clang's whole-program pass otherwise
 * claims zero page from $26 up for hot statics, and everything from
 * $26 to $7F belongs to the kernel or to the app ZP convention.
 * ===================================================================== */

#ifndef CXGEOS_H
#define CXGEOS_H

#define CX_ABI_VERSION  1
#define CX_ABI_SLOTS    85

/* the parameter block's mirror -- see the note above; the real block
 * at $22 is touched only inside cx_run(). Weak, so every translation
 * unit shares one copy under one unmangled name the asm can see. */
/* `used` keeps LTO from discarding what only the asm reads */
__attribute__((weak, used)) volatile unsigned char cx_p[8];
__attribute__((weak, used)) volatile unsigned char cx_a, cx_x, cx_y, cx_c;
__attribute__((weak, used)) volatile unsigned int  cx_slot;


/* --- system --- */
#define CX_VERSION         0x8010   /* -> A/X = ABI version */
#define CX_EXIT            0x8013   /* never returns: back to the shell */

/* --- screen (gfx2, 640x480 @2bpp) --- */
#define CX_GFX_INIT        0x8016   /* - */
#define CX_GFX_CLEAR       0x8019   /* A = colour 0-3 */
#define CX_GFX_PSET        0x801C   /* P0/P1 = x, P2/P3 = y, A = colour (clipped) */
#define CX_GFX_READ        0x801F   /* P0/P1 = x, P2/P3 = y -> A = colour, $FF off screen */
#define CX_GFX_HLINE       0x8022   /* P0/P1 = x, P2/P3 = y, P4/P5 = len, A = colour */
#define CX_GFX_VLINE       0x8025   /* P0/P1 = x, P2/P3 = y, P4/P5 = len, A = colour */
#define CX_GFX_RECT        0x8028   /* P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h, A = colour */
#define CX_GFX_FRAME       0x802B   /* P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h, A = colour */
#define CX_GFX_LINE        0x802E   /* P0/P1 = x0, P2/P3 = y0, P4/P5 = x1, P6/P7 = y1, A = colour */
#define CX_GFX_PATTERN     0x8031   /* A/X = 8x8 pattern, Y = (bg << 2) | fg */
#define CX_GFX_PATRECT     0x8034   /* P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h */
#define CX_GFX_BLIT        0x8037   /* P0/P1 = x, P2/P3 = y, P4 = wbytes, P5 = h, P6/P7 = src, A = op */
#define CX_GFX_BLITM       0x803A   /* P0/P1 = x, P2/P3 = y, P4 = h, P5 = cols, P6/P7 = src */

/* --- text --- */
#define CX_FONT_SET        0x803D   /* A/X = CXF image -> carry set if bad */
#define CX_FONT_STYLE      0x8040   /* A = CX_BOLD | CX_UNDER */
#define CX_FONT_MEASURE    0x8043   /* A/X = string -> P0/P1 = width */
#define CX_FONT_DRAW       0x8046   /* P0/P1 = x, P2/P3 = y, A/X = string -> P0/P1 = pen */

/* --- events --- */
#define CX_EV_HANDLERS     0x8049   /* A/X = a table of CX_EV_COUNT vectors */
#define CX_EV_MAINLOOP     0x804C   /* never returns */
#define CX_EV_DISPATCH     0x804F   /* dispatch one event and return */
#define CX_EV_GET          0x8052   /* -> P0..P7 = a record; carry set if none */
#define CX_EV_POST         0x8055   /* P0..P7 = a record */
#define CX_EV_COUNT        0x8058   /* -> A = records waiting */
#define CX_EV_TIMER        0x805B   /* A = frames between EV_TIMERs (0 = off) */
#define CX_EV_FRAMES       0x805E   /* -> A = the frame counter */

/* --- dirty rectangles --- */
#define CX_DIRTY_RESET     0x8061   /* - */
#define CX_DIRTY_ADD       0x8064   /* P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h */
#define CX_DIRTY_COUNT     0x8067   /* -> A = rects */
#define CX_DIRTY_GET       0x806A   /* A = index -> P0/P1 = x0, P2/P3 = y0, P4/P5 = x1, P6/P7 = y1 */

/* --- the loader --- */
#define CX_APP_LOAD        0x806D   /* A/X = filename, Y = length; returns only on failure: carry, A = 1 not an app / 2 needs a newer kernel */

/* --- events, continued --- */
#define CX_EV_INIT         0x8070   /* clear the queue and hook the raster; an app calls this before cx_ev_handlers */

/* --- menus --- */
#define CX_MENU_SET        0x8073   /* A/X = the menu bar (docs/formats.md); draws it, owns the top strip; carry = region stack full */
#define CX_MENU_OFF        0x8076   /* forget the menu; only with no menu open */

/* --- the pointer --- */
#define CX_MOUSE_SHOW      0x8079   /* A = the pointer number (1 = the arrow), or $FF to show without setting one; the loader hides it between apps, so an app that wants it asks */
#define CX_MOUSE_HIDE      0x807C   /* - */

/* --- themes and dialogs --- */
#define CX_THEME_SET       0x807F   /* A/X = a 12-byte theme record (docs/formats.md): four palette RGBs plus the role indices; the palette changes instantly */
#define CX_DLG_ALERT       0x8082   /* A/X = a dialog descriptor (docs/formats.md); SYNCHRONOUS -- returns A = the chosen button. RETURN picks button 0 */

/* --- widgets --- */
#define CX_WG_SET          0x8085   /* A/X = a widget list (docs/formats.md); draws it, routes its clicks; posts EV_WIDGET(detail = index, P2 = value) */
#define CX_WG_DRAW         0x8088   /* redraw the current widget list */

/* --- keyboard menu nav --- */
#define CX_MENU_KEY        0x808B   /* A = a key; drives the menu bar (DOWN opens, arrows move, RETURN picks, ESC dismisses). Carry set if it was a menu key; clobbers X and Y. Call it from your EV_KEY handler */

/* --- keyboard widget focus --- */
#define CX_WG_KEY          0x808E   /* A = a key; TAB/UP move focus, SPACE/RETURN activate, LEFT/RIGHT step a scrollbar, printable keys type into a focused field. Carry set if it was a widget key; clobbers X and Y. Call from EV_KEY */

/* --- the directory --- */
#define CX_DIR_OPEN        0x8091   /* A/X = a pattern like "$", Y = length; opens the directory channel. Carry set on a DOS error */
#define CX_DIR_NEXT        0x8094   /* P0/P1 = a >=17-byte buffer; fills the entry's name, A = 0 file / 1 dir. Carry set = listing done. The first entry is the volume header */
#define CX_DIR_CLOSE       0x8097   /* close the directory channel */

/* --- the DOS command channel --- */
#define CX_DOS_CMD         0x809A   /* A/X = a CMDR-DOS command ("S:F", "R:NEW=OLD", "MD:D", "CD:D"...), Y = length -> A = status code, carry set when it is an error (>= 20); the reply text waits for cx_dos_msg */
#define CX_DOS_MSG         0x809D   /* P0/P1 = a >=64-byte buffer; copies the last DOS reply ("62,FILE NOT FOUND,00,00"), NUL-terminated -> A = its length */

/* --- dialogs, continued --- */
#define CX_DLG_PROMPT      0x80A0   /* A/X = message, P0/P1 = a NUL-terminated buffer (may be seeded), P2 = its capacity; SYNCHRONOUS one-line editor with ok/cancel -> A = the length, carry set if cancelled. RETURN is ok, ESC is cancel */

/* --- the clipboard --- */
#define CX_CLIP_PUT        0x80A3   /* A = type (1 = TEXT; 0 or length 0 empties), P0/P1 = source, P2/P3 = length -> carry set if too big (~32KB fits) */
#define CX_CLIP_GET        0x80A6   /* P0/P1 = destination, P2/P3 = its capacity -> A = the type (0 = empty), P2/P3 = the length copied (what is held or what fits, whichever is less) */
#define CX_CLIP_TYPE       0x80A9   /* -> A = the type waiting (0 = empty), P2/P3 = its length; nothing is consumed */

/* --- desk accessories --- */
#define CX_DA_OPEN         0x80AC   /* A/X = a .CXD's name, Y = length: load it into bank 9 and open its window over the running app. Carry set = would not load / not a DA. One at a time; no dialogs while one is up (they share banks 14-15) */
#define CX_DA_CLOSE        0x80AF   /* put the handlers, the region and the pixels back; the DA usually calls this itself on its exit key */

/* --- events, continued --- */
#define CX_EV_NEXT         0x80B2   /* -> P0..P7 = the next non-mouse event; mouse events are routed to the toolkit first; carry set if the queue emptied with none to return */

/* --- audio: the VERA PSG (16 voices) --- */
#define CX_PSG_INIT        0x80B5   /* silence all 16 voices */
#define CX_PSG_FREQ        0x80B8   /* X = voice (0-15), P0/P1 = frequency word */
#define CX_PSG_VOL         0x80BB   /* X = voice, A = volume (0-63), Y = pan (0x40 left / 0x80 right / 0xC0 both) */
#define CX_PSG_WAVE        0x80BE   /* X = voice, A = waveform (0x00 pulse / 0x40 saw / 0x80 triangle / 0xC0 noise), Y = pulse width (0-63) */
#define CX_PSG_OFF         0x80C1   /* X = voice; volume to zero, panning kept */

/* --- audio: the YM2151 FM chip (through the ROM audio driver, bank-switched) --- */
#define CX_YM_INIT         0x80C4   /* reset the chip and load the default instrument patches */
#define CX_YM_NOTE         0x80C7   /* A = channel (0-7), X = (octave << 4) | note (1-12); X=0 releases. Retriggers the envelope */
#define CX_YM_OFF          0x80CA   /* A = channel; release the note */
#define CX_YM_VOL          0x80CD   /* A = channel, X = attenuation (0 = the patch's own volume, larger = quieter) */
#define CX_YM_PATCH        0x80D0   /* A = channel, X = a ROM patch index (0-162) */

/* --- sprites (VERA hardware sprites) --- */
#define CX_SPRITE_IMAGE    0x80D3   /* X = sprite (1-127), P0 = addr low, P1 = addr mid, P2 = addr bit 16, A = mode (0 = 4bpp, 0x80 = 8bpp) */
#define CX_SPRITE_POS      0x80D6   /* X = sprite, P0/P1 = x (0-1023), P2/P3 = y */
#define CX_SPRITE_SIZE     0x80D9   /* X = sprite, A = width code (0=8, 1=16, 2=32, 3=64), Y = height code, P0 = palette offset (0-15) */
#define CX_SPRITE_FLAGS    0x80DC   /* X = sprite, A = collision<<4 | Z(0/4/8/0xC) | vflip<<1 | hflip; a full write (needed once before cx_sprite_z) */
#define CX_SPRITE_Z        0x80DF   /* X = sprite, A = Z-depth only (0 hides, 4 behind, 8 middle, 0xC front); read-modify-write, so write the flags once first */

/* --- PCM audio (the VERA 4KB FIFO, refilled each frame from the event IRQ) --- */
#define CX_PCM_CTRL        0x80E2   /* A = control byte: volume 0-15 | 0x20 16-bit | 0x10 stereo */
#define CX_PCM_PLAY        0x80E5   /* P0/P1 = sample source, P2/P3 = byte count, A = rate (1-128, 128 = 48 kHz); resets the FIFO, primes it, starts playback */
#define CX_PCM_STOP        0x80E8   /* silence and forget the current sample */
#define CX_PCM_ACTIVE      0x80EB   /* -> A = 1 while a sample is still playing, else 0 */

/* --- joysticks (SNES pads; pad 0 is the keyboard joystick) --- */
#define CX_JOY_GET         0x80EE   /* A = pad (0-4) -> A = buttons low, X = buttons high; carry set if the pad is absent. Pad 0's presence tracks a PHYSICAL pad -- its keyboard-driven data is valid even when carry says absent */
#define CX_JOY_ENABLE      0x80F1   /* A = a mask of pads (bit n = pad n, 0-3; 0 = off): scan each frame and post EV_JOY (type 9, detail = pad, P2/P3 = buttons, P4/P5 = changed bits) whenever a pad's state changes */

/* --- the graphics port --- */
#define CX_GFX_MODE        0x80F4   /* A = the mode -> carry set if unknown; swaps the engine and runs its init (VERA is reprogrammed, the screen is the new mode's) */
#define CX_GFX_INFO        0x80F7   /* -> A = mode, P0/P1 = width, P2/P3 = height, P4 = bpp, P5/P6 = bytes per row */

/* --- shapes (every mode: they draw through the port itself) --- */
#define CX_GFX_CIRCLE      0x80FA   /* P0/P1 = cx, P2/P3 = cy, P4 = r (0-255), A = colour: an outline through the port's pset, clipped where pset clips */
#define CX_GFX_DISC        0x80FD   /* same arguments, filled with spans; no clipping -- keep it on screen */
#define CX_GFX_FLOOD       0x8100   /* P0/P1 = x, P2/P3 = y, A = colour: scanline fill of the region holding the seed, fenced by differing pixels and the canvas edge; carry set if the seed stack overflowed */

/* --- tiles (mode 2 only: the tile personality's own API) --- */
#define CX_TILE_SETUP      0x8103   /* A = layer (0/1): the ledger config (64x32 map, 8x8 4bpp tiles) and the layer on. Carry set outside mode 2 */
#define CX_TILE_SCROLL     0x8106   /* A = layer, P0/P1 = hscroll, P2/P3 = vscroll (0-4095) */
#define CX_TILE_CELL       0x8109   /* A = layer, X = col (0-63), Y = row (0-31), P0/P1 = the cell word (index; hi: pal<<4 | vflip<<3 | hflip<<2 | index 9:8) */
#define CX_TILE_FILL       0x810C   /* A = layer, P0/P1 = the cell word, into every cell */

/* The crossing itself. The slot address is parked in __rc2/3 before
 * anything moves; $22-$25 ride the hardware stack; the mirror is
 * copied in, A/X/Y loaded, the slot called through a trampoline, and
 * registers, carry and the block all copied back out. An event IRQ
 * landing mid-crossing is fine: the kernel's handler saves and
 * restores the whole $02-$31 range around itself. */
__attribute__((weak, noinline)) void cx_run(void) {
    asm volatile(
        "lda cx_slot\n\t"
        "sta __rc2\n\t"
        "lda cx_slot+1\n\t"
        "sta __rc3\n\t"
        "lda 0x22\n\tpha\n\t"
        "lda 0x23\n\tpha\n\t"
        "lda 0x24\n\tpha\n\t"
        "lda 0x25\n\tpha\n\t"
        "ldy #7\n\t"
        "1:\n\t"
        "lda cx_p,y\n\t"
        "sta 0x22,y\n\t"
        "dey\n\t"
        "bpl 1b\n\t"
        "ldy cx_y\n\t"
        "ldx cx_x\n\t"
        "lda cx_a\n\t"
        "jsr 2f\n\t"
        "sta cx_a\n\t"
        "stx cx_x\n\t"
        "php\n\t"
        "pla\n\t"
        "and #1\n\t"
        "sta cx_c\n\t"
        "ldy #7\n\t"
        "3:\n\t"
        "lda 0x22,y\n\t"
        "sta cx_p,y\n\t"
        "dey\n\t"
        "bpl 3b\n\t"
        "pla\n\tsta 0x25\n\t"
        "pla\n\tsta 0x24\n\t"
        "pla\n\tsta 0x23\n\t"
        "pla\n\tsta 0x22\n\t"
        "bra 4f\n\t"
        "2:\n\t"
        "jmp (__rc2)\n\t"
        "4:"
        ::: "a", "x", "y", "cc", "memory");
}

#define cx_call(slot)          (cx_slot = (slot), cx_run())
#define cx_call_a(slot, a)     (cx_a = (unsigned char)(a), cx_call(slot))
#define cx_call_ax(slot, a, x) (cx_a = (unsigned char)(a), cx_x = (unsigned char)(x), cx_call(slot))
#define cx_call_p(slot, ptr)   cx_call_ax((slot), ((unsigned int)(ptr)) & 0xFF, ((unsigned int)(ptr)) >> 8)
#define cx_ret(slot)           (cx_call(slot), cx_a)
#define cx_ret16(slot)         (cx_call(slot), (unsigned int)cx_a | ((unsigned int)cx_x << 8))

#endif /* CXGEOS_H */
