; vasm6502_oldstyle -- GENERATED by abi/gen_bindings.py. Do not edit.
; =====================================================================
; CXRF vbcc crossing -- the parameter-block bridge for a vbcc C app
; =====================================================================
; The proven cc65/oscar64/kickc shape -- save the low zero page, lay the
; mirror across the block at $22-$29, call the slot, read A/X/carry and the
; block back, restore the ZP -- in vasm oldstyle syntax with vbcc's leading-
; '_' C symbol naming (x16_clib src_vbcc is the ABI reference). Link it:
;   vc +x16 -Iinc app.c sdk/include_vbcc/cxrun.s -o APP.PRG
; =====================================================================

        global  _cx_run
        global  _cx_p, _cx_a, _cx_x, _cx_y, _cx_c, _cx_slot

        section bss
_cx_p:      ds 8
_cx_a:      ds 1
_cx_x:      ds 1
_cx_y:      ds 1
_cx_c:      ds 1
_cx_slot:   ds 2
cx_zpsave:  ds 126        ; $02..$7F, saved across a call

        section text
_cx_run:
        ldx #0
cxsv:
        lda $02,x
        sta cx_zpsave,x
        inx
        cpx #126
        bne cxsv
        ldx #0
cxin:
        lda _cx_p,x         ; the mirror -> the real block $22..$29
        sta $22,x
        inx
        cpx #8
        bne cxin
        ldy _cx_y           ; A/X/Y in
        ldx _cx_x
        lda _cx_a
        jsr cxjs
        sta _cx_a           ; A, X and the carry back out
        stx _cx_x
        php
        pla
        and #1
        sta _cx_c
        ldx #0
cxout:
        lda $22,x           ; the block back into the mirror
        sta _cx_p,x
        inx
        cpx #8
        bne cxout
        ldx #0
cxrs:
        lda cx_zpsave,x     ; restore the zero page
        sta $02,x
        inx
        cpx #126
        bne cxrs
        jmp cxdn
cxjs:
        jmp (_cx_slot)      ; _cx_slot HOLDS the slot address; jump to it
cxdn:
        rts
