; ca65 -- GENERATED by abi/gen_bindings.py. Do not edit.
; =====================================================================
; CXGEOS :: kernel/resident/jumptab.asm -- the ABI
; =====================================================================
; Every app reaches the kernel through here and nowhere else. The
; address of each JMP is fixed forever: slot n is at $8010 + n*3.
;
; Edit abi/cxgeos.abi and regenerate.
; =====================================================================

; pushseg/popseg so including this cannot change the caller's
; segment. Without them everything after the include lands in
; JUMPTAB, and ld65 reports it as the table overflowing --
; which is a long way from what actually went wrong.
.pushseg
.segment "JUMPHDR"
cx_hdr_magic
    .byte "CXOS"                  ; the loader looks for this
cx_hdr_version
    .word 1                    ; ABI version
cx_hdr_slots
    .word 55                    ; slots
cx_hdr_init
    .word cx_init               ; the loader starts here
    .res 6, 0                   ; reserved

.segment "JUMPTAB"
cx_jumptab

; --- system ------------------------------------------------------
    jmp cx_do_version    ;  0  -> A/X = ABI version
    jmp cx_do_exit       ;  1  never returns: back to the shell

; --- screen (gfx2, 640x480 @2bpp) --------------------------------
    jmp gfx2_init        ;  2  -
    jmp gfx2_clear       ;  3  A = colour 0-3
    jmp gfx2_pset        ;  4  P0/P1 = x, P2/P3 = y, A = colour (clipped)
    jmp gfx2_read        ;  5  P0/P1 = x, P2/P3 = y -> A = colour, $FF off screen
    jmp gfx2_hline       ;  6  P0/P1 = x, P2/P3 = y, P4/P5 = len, A = colour
    jmp gfx2_vline       ;  7  P0/P1 = x, P2/P3 = y, P4/P5 = len, A = colour
    jmp gfx2_rect        ;  8  P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h, A = colour
    jmp gfx2_frame       ;  9  P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h, A = colour
    jmp gfx2_line        ; 10  P0/P1 = x0, P2/P3 = y0, P4/P5 = x1, P6/P7 = y1, A = colour
    jmp gfx2_pattern_set ; 11  A/X = 8x8 pattern, Y = (bg << 2) | fg
    jmp gfx2_pattern_rect ; 12  P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h
    jmp gfx2_blit        ; 13  P0/P1 = x, P2/P3 = y, P4 = wbytes, P5 = h, P6/P7 = src, A = op
    jmp gfx2_blitm       ; 14  P0/P1 = x, P2/P3 = y, P4 = h, P5 = cols, P6/P7 = src

; --- text --------------------------------------------------------
    jmp font_set         ; 15  A/X = CXF image -> carry set if bad
    jmp font_style       ; 16  A = CX_BOLD | CX_UNDER
    jmp font_measure     ; 17  A/X = string -> P0/P1 = width
    jmp font_draw        ; 18  P0/P1 = x, P2/P3 = y, A/X = string -> P0/P1 = pen

; --- events ------------------------------------------------------
    jmp ev_handlers      ; 19  A/X = a table of CX_EV_COUNT vectors
    jmp ev_mainloop      ; 20  never returns
    jmp ev_dispatch      ; 21  dispatch one event and return
    jmp ev_get           ; 22  -> P0..P7 = a record; carry set if none
    jmp ev_post          ; 23  P0..P7 = a record
    jmp ev_count         ; 24  -> A = records waiting
    jmp ev_timer         ; 25  A = frames between EV_TIMERs (0 = off)
    jmp ev_frames        ; 26  -> A = the frame counter

; --- dirty rectangles --------------------------------------------
    jmp dr_reset         ; 27  -
    jmp dr_add           ; 28  P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h
    jmp dr_count         ; 29  -> A = rects
    jmp dr_get           ; 30  A = index -> P0/P1 = x0, P2/P3 = y0, P4/P5 = x1, P6/P7 = y1

; --- the loader --------------------------------------------------
    jmp cxl_load         ; 31  A/X = filename, Y = length; returns only on failure: carry, A = 1 not an app / 2 needs a newer kernel

; --- events, continued -------------------------------------------
    jmp ev_init          ; 32  clear the queue and hook the raster; an app calls this before cx_ev_handlers

; --- menus -------------------------------------------------------
    jmp cx_do_menu_set   ; 33  A/X = the menu bar (docs/formats.md); draws it, owns the top strip; carry = region stack full
    jmp cx_do_menu_off   ; 34  forget the menu; only with no menu open

; --- the pointer -------------------------------------------------
    jmp cx_do_mouse_show ; 35  A = the pointer number (1 = the arrow), or $FF to show without setting one; the loader hides it between apps, so an app that wants it asks
    jmp mouse_hide       ; 36  -

; --- themes and dialogs ------------------------------------------
    jmp cx_do_theme_set  ; 37  A/X = a 12-byte theme record (docs/formats.md): four palette RGBs plus the role indices; the palette changes instantly
    jmp cx_do_dlg_alert  ; 38  A/X = a dialog descriptor (docs/formats.md); SYNCHRONOUS -- returns A = the chosen button. RETURN picks button 0

; --- widgets -----------------------------------------------------
    jmp cx_do_wg_set     ; 39  A/X = a widget list (docs/formats.md); draws it, routes its clicks; posts EV_WIDGET(detail = index, P2 = value)
    jmp cx_do_wg_draw    ; 40  redraw the current widget list

; --- keyboard menu nav -------------------------------------------
    jmp cx_do_menu_key   ; 41  A = a key; drives the menu bar (DOWN opens, arrows move, RETURN picks, ESC dismisses). Carry set if it was a menu key; clobbers X and Y. Call it from your EV_KEY handler

; --- keyboard widget focus ---------------------------------------
    jmp cx_do_wg_key     ; 42  A = a key; TAB/UP move focus, SPACE/RETURN activate, LEFT/RIGHT step a scrollbar, printable keys type into a focused field. Carry set if it was a widget key; clobbers X and Y. Call from EV_KEY

; --- the directory -----------------------------------------------
    jmp cx_dir_open      ; 43  A/X = a pattern like "$", Y = length; opens the directory channel. Carry set on a DOS error
    jmp cx_dir_next      ; 44  P0/P1 = a >=17-byte buffer; fills the entry's name, A = 0 file / 1 dir. Carry set = listing done. The first entry is the volume header
    jmp cx_dir_close     ; 45  close the directory channel

; --- the DOS command channel -------------------------------------
    jmp cx_do_dos_cmd    ; 46  A/X = a CMDR-DOS command ("S:F", "R:NEW=OLD", "MD:D", "CD:D"...), Y = length -> A = status code, carry set when it is an error (>= 20); the reply text waits for cx_dos_msg
    jmp cx_do_dos_msg    ; 47  P0/P1 = a >=64-byte buffer; copies the last DOS reply ("62,FILE NOT FOUND,00,00"), NUL-terminated -> A = its length

; --- dialogs, continued ------------------------------------------
    jmp cx_do_dlg_prompt ; 48  A/X = message, P0/P1 = a NUL-terminated buffer (may be seeded), P2 = its capacity; SYNCHRONOUS one-line editor with ok/cancel -> A = the length, carry set if cancelled. RETURN is ok, ESC is cancel

; --- the clipboard -----------------------------------------------
    jmp cx_do_clip_put   ; 49  A = type (1 = TEXT; 0 or length 0 empties), P0/P1 = source, P2/P3 = length -> carry set if too big (~32KB fits)
    jmp cx_do_clip_get   ; 50  P0/P1 = destination, P2/P3 = its capacity -> A = the type (0 = empty), P2/P3 = the length copied (what is held or what fits, whichever is less)
    jmp cx_do_clip_type  ; 51  -> A = the type waiting (0 = empty), P2/P3 = its length; nothing is consumed

; --- desk accessories --------------------------------------------
    jmp cx_do_da_open    ; 52  A/X = a .CXD's name, Y = length: load it into bank 9 and open its window over the running app. Carry set = would not load / not a DA. One at a time; no dialogs while one is up (they share banks 14-15)
    jmp cx_do_da_close   ; 53  put the handlers, the region and the pixels back; the DA usually calls this itself on its exit key

; --- events, continued -------------------------------------------
    jmp ev_next          ; 54  -> P0..P7 = the next non-mouse event; mouse events are routed to the toolkit first; carry set if the queue emptied with none to return

.popseg

