; ca65 -- GENERATED by abi/gen_bindings.py. Do not edit.
; =====================================================================
; CXGEOS :: kernel/resident/jumptab.asm -- the ABI
; =====================================================================
; Every app reaches the kernel through here and nowhere else. The
; address of each JMP is fixed forever: slot n is at $8010 + n*3.
;
; Edit abi/cxgeos.abi and regenerate.
; =====================================================================

; pushseg/popseg so including this cannot change the caller's
; segment. Without them everything after the include lands in
; JUMPTAB, and ld65 reports it as the table overflowing --
; which is a long way from what actually went wrong.
.pushseg
.segment "JUMPHDR"
cx_hdr_magic
    .byte "CXOS"                  ; the loader looks for this
cx_hdr_version
    .word 1                    ; ABI version
cx_hdr_slots
    .word 93                    ; slots
cx_hdr_init
    .word cx_init               ; the loader starts here
    .res 6, 0                   ; reserved

.segment "JUMPTAB"
cx_jumptab

; --- system ------------------------------------------------------
    jmp cx_do_version    ;  0  -> A/X = ABI version
    jmp cx_do_exit       ;  1  never returns: back to the shell

; --- screen (gfx2, 640x480 @2bpp) --------------------------------
    jmp cx_do_gfx_init   ;  2  -
    jmp cxov_clear       ;  3  A = colour 0-3
    jmp cxov_pset        ;  4  P0/P1 = x, P2/P3 = y, A = colour (clipped)
    jmp cxov_read        ;  5  P0/P1 = x, P2/P3 = y -> A = colour, $FF off screen
    jmp cxov_hline       ;  6  P0/P1 = x, P2/P3 = y, P4/P5 = len, A = colour
    jmp cxov_vline       ;  7  P0/P1 = x, P2/P3 = y, P4/P5 = len, A = colour
    jmp cxov_rect        ;  8  P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h, A = colour
    jmp cxov_frame       ;  9  P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h, A = colour
    jmp cxov_line        ; 10  P0/P1 = x0, P2/P3 = y0, P4/P5 = x1, P6/P7 = y1, A = colour
    jmp cxov_pattern     ; 11  A/X = 8x8 pattern, Y = (bg << 2) | fg
    jmp cxov_patrect     ; 12  P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h
    jmp cxov_blit        ; 13  P0/P1 = x, P2/P3 = y, P4 = wbytes, P5 = h, P6/P7 = src, A = op
    jmp cxov_blitm       ; 14  P0/P1 = x, P2/P3 = y, P4 = h, P5 = cols, P6/P7 = src

; --- text --------------------------------------------------------
    jmp cx_g_font_set    ; 15  A/X = CXF image -> carry set if bad
    jmp cx_g_font_style  ; 16  A = CX_BOLD | CX_UNDER
    jmp cxov_measure     ; 17  A/X = string -> P0/P1 = width
    jmp cxov_text        ; 18  P0/P1 = x, P2/P3 = y, A/X = string -> P0/P1 = pen

; --- events ------------------------------------------------------
    jmp ev_handlers      ; 19  A/X = a table of CX_EV_COUNT vectors
    jmp ev_mainloop      ; 20  never returns
    jmp ev_dispatch      ; 21  dispatch one event and return
    jmp ev_get           ; 22  -> P0..P7 = a record; carry set if none
    jmp ev_post          ; 23  P0..P7 = a record
    jmp ev_count         ; 24  -> A = records waiting
    jmp ev_timer         ; 25  A = frames between EV_TIMERs (0 = off)
    jmp ev_frames        ; 26  -> A = the frame counter

; --- dirty rectangles --------------------------------------------
    jmp cx_do_dirty_reset ; 27  -
    jmp cx_do_dirty_add  ; 28  P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h
    jmp cx_do_dirty_count ; 29  -> A = rects
    jmp cx_do_dirty_get  ; 30  A = index -> P0/P1 = x0, P2/P3 = y0, P4/P5 = x1, P6/P7 = y1

; --- the loader --------------------------------------------------
    jmp cxl_load         ; 31  A/X = filename, Y = length; returns only on failure: carry, A = 1 not an app / 2 needs a newer kernel

; --- events, continued -------------------------------------------
    jmp ev_init          ; 32  clear the queue and hook the raster; an app calls this before cx_ev_handlers

; --- menus -------------------------------------------------------
    jmp cx_g_menu_set    ; 33  A/X = the menu bar (docs/formats.md); draws it, owns the top strip; carry = region stack full
    jmp cx_g_menu_off    ; 34  forget the menu; only with no menu open

; --- the pointer -------------------------------------------------
    jmp cx_do_mouse_show ; 35  A = the pointer number (1 = the arrow), or $FF to show without setting one; the loader hides it between apps, so an app that wants it asks
    jmp mouse_hide       ; 36  -

; --- themes and dialogs ------------------------------------------
    jmp cx_g_theme_set   ; 37  A/X = a 12-byte theme record (docs/formats.md): four palette RGBs plus the role indices; the palette changes instantly
    jmp cx_g_dlg_alert   ; 38  A/X = a dialog descriptor (docs/formats.md); SYNCHRONOUS -- returns A = the chosen button. RETURN picks button 0

; --- widgets -----------------------------------------------------
    jmp cx_g_wg_set      ; 39  A/X = a widget list (docs/formats.md); draws it, routes its clicks; posts EV_WIDGET(detail = index, P2 = value)
    jmp cx_g_wg_draw     ; 40  redraw the current widget list

; --- keyboard menu nav -------------------------------------------
    jmp cx_g_menu_key    ; 41  A = a key; drives the menu bar (DOWN opens, arrows move, RETURN picks, ESC dismisses). Carry set if it was a menu key; clobbers X and Y. Call it from your EV_KEY handler

; --- keyboard widget focus ---------------------------------------
    jmp cx_g_wg_key      ; 42  A = a key; TAB/UP move focus, SPACE/RETURN activate, LEFT/RIGHT step a scrollbar, printable keys type into a focused field. Carry set if it was a widget key; clobbers X and Y. Call from EV_KEY

; --- the directory -----------------------------------------------
    jmp cx_do_dir_open   ; 43  A/X = a pattern like "$", Y = length; opens the directory channel. Carry set on a DOS error
    jmp cx_do_dir_next   ; 44  P0/P1 = a >=17-byte buffer; fills the entry's name, A = 0 file / 1 dir. Carry set = listing done. The first entry is the volume header
    jmp cx_do_dir_close  ; 45  close the directory channel

; --- the DOS command channel -------------------------------------
    jmp cx_do_dos_cmd    ; 46  A/X = a CMDR-DOS command ("S:F", "R:NEW=OLD", "MD:D", "CD:D"...), Y = length -> A = status code, carry set when it is an error (>= 20); the reply text waits for cx_dos_msg
    jmp cx_do_dos_msg    ; 47  P0/P1 = a >=64-byte buffer; copies the last DOS reply ("62,FILE NOT FOUND,00,00"), NUL-terminated -> A = its length

; --- dialogs, continued ------------------------------------------
    jmp cx_g_dlg_prompt  ; 48  A/X = message, P0/P1 = a NUL-terminated buffer (may be seeded), P2 = its capacity; SYNCHRONOUS one-line editor with ok/cancel -> A = the length, carry set if cancelled. RETURN is ok, ESC is cancel

; --- the clipboard -----------------------------------------------
    jmp cx_do_clip_put   ; 49  A = type (1 = TEXT; 0 or length 0 empties), P0/P1 = source, P2/P3 = length -> carry set if too big (~32KB fits)
    jmp cx_do_clip_get   ; 50  P0/P1 = destination, P2/P3 = its capacity -> A = the type (0 = empty), P2/P3 = the length copied (what is held or what fits, whichever is less)
    jmp cx_do_clip_type  ; 51  -> A = the type waiting (0 = empty), P2/P3 = its length; nothing is consumed

; --- desk accessories --------------------------------------------
    jmp cx_g_da_open     ; 52  A/X = a .CXD's name, Y = length: load it into bank 9 and open its window over the running app. Carry set = would not load / not a DA. One at a time; no dialogs while one is up (they share banks 14-15)
    jmp cx_g_da_close    ; 53  put the handlers, the region and the pixels back; the DA usually calls this itself on its exit key

; --- events, continued -------------------------------------------
    jmp ev_next          ; 54  -> P0..P7 = the next non-mouse event; mouse events are routed to the toolkit first; carry set if the queue emptied with none to return

; --- audio: the VERA PSG (16 voices) -----------------------------
    jmp cx_do_psg_init   ; 55  silence all 16 voices
    jmp cx_do_psg_freq   ; 56  X = voice (0-15), P0/P1 = frequency word
    jmp cx_do_psg_vol    ; 57  X = voice, A = volume (0-63), Y = pan (0x40 left / 0x80 right / 0xC0 both)
    jmp cx_do_psg_wave   ; 58  X = voice, A = waveform (0x00 pulse / 0x40 saw / 0x80 triangle / 0xC0 noise), Y = pulse width (0-63)
    jmp cx_do_psg_off    ; 59  X = voice; volume to zero, panning kept

; --- audio: the YM2151 FM chip (through the ROM audio driver, bank-switched) 
    jmp cx_do_ym_init    ; 60  reset the chip and load the default instrument patches
    jmp cx_do_ym_note    ; 61  A = channel (0-7), X = (octave << 4) | note (1-12); X=0 releases. Retriggers the envelope
    jmp cx_do_ym_off     ; 62  A = channel; release the note
    jmp cx_do_ym_vol     ; 63  A = channel, X = attenuation (0 = the patch's own volume, larger = quieter)
    jmp cx_do_ym_patch   ; 64  A = channel, X = a ROM patch index (0-162)

; --- sprites (VERA hardware sprites) -----------------------------
    jmp cx_do_sprite_image ; 65  X = sprite (1-127), P0 = addr low, P1 = addr mid, P2 = addr bit 16, A = mode (0 = 4bpp, 0x80 = 8bpp)
    jmp cx_do_sprite_pos ; 66  X = sprite, P0/P1 = x (0-1023), P2/P3 = y
    jmp cx_do_sprite_size ; 67  X = sprite, A = width code (0=8, 1=16, 2=32, 3=64), Y = height code, P0 = palette offset (0-15)
    jmp cx_do_sprite_flags ; 68  X = sprite, A = collision<<4 | Z(0/4/8/0xC) | vflip<<1 | hflip; a full write (needed once before cx_sprite_z)
    jmp cx_do_sprite_z   ; 69  X = sprite, A = Z-depth only (0 hides, 4 behind, 8 middle, 0xC front); read-modify-write, so write the flags once first

; --- PCM audio (the VERA 4KB FIFO, refilled each frame from the event IRQ) 
    jmp cx_do_pcm_ctrl   ; 70  A = control byte: volume 0-15 | 0x20 16-bit | 0x10 stereo
    jmp cx_do_pcm_play   ; 71  P0/P1 = sample source, P2/P3 = byte count, A = rate (1-128, 128 = 48 kHz); resets the FIFO, primes it, starts playback
    jmp cx_do_pcm_stop   ; 72  silence and forget the current sample
    jmp cx_do_pcm_active ; 73  -> A = 1 while a sample is still playing, else 0

; --- joysticks (SNES pads; pad 0 is the keyboard joystick) -------
    jmp cx_do_joy_get    ; 74  A = pad (0-4) -> A = buttons low, X = buttons high; carry set if the pad is absent. Pad 0's presence tracks a PHYSICAL pad -- its keyboard-driven data is valid even when carry says absent
    jmp ev_joy_enable    ; 75  A = a mask of pads (bit n = pad n, 0-3; 0 = off): scan each frame and post EV_JOY (type 9, detail = pad, P2/P3 = buttons, P4/P5 = changed bits) whenever a pad's state changes

; --- the graphics port -------------------------------------------
    jmp cx_do_gfx_mode   ; 76  A = the mode -> carry set if unknown; swaps the engine and runs its init (VERA is reprogrammed, the screen is the new mode's)
    jmp cx_do_gfx_info   ; 77  -> A = mode, P0/P1 = width, P2/P3 = height, P4 = bpp, P5/P6 = bytes per row

; --- shapes (every mode: they draw through the port itself) ------
    jmp cx_do_gfx_circle ; 78  P0/P1 = cx, P2/P3 = cy, P4 = r (0-255), A = colour: an outline through the port's pset, clipped where pset clips
    jmp cx_do_gfx_disc   ; 79  same arguments, filled with spans; no clipping -- keep it on screen
    jmp cx_do_gfx_flood  ; 80  P0/P1 = x, P2/P3 = y, A = colour: scanline fill of the region holding the seed, fenced by differing pixels and the canvas edge; carry set if the seed stack overflowed

; --- tiles (mode 2 only: the tile personality's own API) ---------
    jmp cx_do_tile_setup ; 81  A = layer (0/1): the ledger config (64x32 map, 8x8 4bpp tiles) and the layer on. Carry set outside mode 2
    jmp cx_do_tile_scroll ; 82  A = layer, P0/P1 = hscroll, P2/P3 = vscroll (0-4095)
    jmp cx_do_tile_cell  ; 83  A = layer, X = col (0-63), Y = row (0-31), P0/P1 = the cell word (index; hi: pal<<4 | vflip<<3 | hflip<<2 | index 9:8)
    jmp cx_do_tile_fill  ; 84  A = layer, P0/P1 = the cell word, into every cell

; --- ellipses (every mode, like slots 78-80: they draw through the port) 
    jmp cx_do_gfx_ellipse ; 85  P0/P1 = cx, P2/P3 = cy, P4 = rx, P5 = ry (each 0-255), A = colour: an axis-aligned outline through the port's pset, clipped where pset clips
    jmp cx_do_gfx_fellipse ; 86  same arguments, filled with spans; no clipping -- keep it on screen

; --- event sources -----------------------------------------------
    jmp ev_set_mask      ; 87  A = a bit mask of sampled sources: bit 0 = mouse, bit 1 = keyboard. With both off and the pads off, the frame tick costs only the timer/PCM gates

; --- pluggable assets --------------------------------------------
    jmp cx_do_file_load  ; 88  A/X = filename, Y = length, P0/P1 = destination, P2/P3 = capacity -> carry clear, P4/P5 = bytes read; carry set, A = 1 not there / 2 read error / 3 bigger than the capacity (the first P4/P5 bytes are in)
    jmp cx_do_ink        ; 89  A = the text ink for the CURRENT mode: a palette index in mode 1, an attribute (0-15) in mode 3; mode 0's text ink belongs to the theme and ignores it

; --- asset loaders (the shapes every X16 exporter already emits) -
    jmp cx_do_vload      ; 90  A/X = filename, Y = length, P0/P1 = VRAM address, P2 = VRAM bank (0/1), P3 bit0 = raw -> carry clear, P4/P5 = one past the last byte; carry set, A = the KERNAL error
    jmp cx_do_bload      ; 91  A/X = filename, Y = length, P0 = RAM bank (16+; the kernel's banks refuse with A = 0), P1/P2 = address, P3 bit0 = raw -> carry clear, P4/P5 = one past the last byte, P6 = the end bank; carry set, A = the error

; --- modal panel (a form: your widgets in a box, with confirm/cancel) 
    jmp cx_g_panel       ; 92  A/X = a panel descriptor (docs/formats.md); SYNCHRONOUS -- draws the box and its widgets, runs modal, returns A = the chosen button (0 = the confirm/RETURN button)

.popseg

