; ca65 -- GENERATED by abi/gen_bindings.py. Do not edit.
; =====================================================================
; CXGEOS :: kernel/resident/jumptab.asm -- the ABI
; =====================================================================
; Every app reaches the kernel through here and nowhere else. The
; address of each JMP is fixed forever: slot n is at $8010 + n*3.
;
; Edit abi/cxgeos.abi and regenerate.
; =====================================================================

; pushseg/popseg so including this cannot change the caller's
; segment. Without them everything after the include lands in
; JUMPTAB, and ld65 reports it as the table overflowing --
; which is a long way from what actually went wrong.
.pushseg
.segment "JUMPHDR"
cx_hdr_magic
    .byte "CXOS"                  ; the loader looks for this
cx_hdr_version
    .word 1                    ; ABI version
cx_hdr_slots
    .word 42                    ; slots
cx_hdr_init
    .word cx_init               ; the loader starts here
    .res 6, 0                   ; reserved

.segment "JUMPTAB"
cx_jumptab

; --- system ------------------------------------------------------
    jmp cx_do_version    ;  0  -> A/X = ABI version
    jmp cx_do_exit       ;  1  never returns: back to the shell

; --- screen (gfx2, 640x480 @2bpp) --------------------------------
    jmp gfx2_init        ;  2  -
    jmp gfx2_clear       ;  3  A = colour 0-3
    jmp gfx2_pset        ;  4  P0/P1 = x, P2/P3 = y, A = colour (clipped)
    jmp gfx2_read        ;  5  P0/P1 = x, P2/P3 = y -> A = colour, $FF off screen
    jmp gfx2_hline       ;  6  P0/P1 = x, P2/P3 = y, P4/P5 = len, A = colour
    jmp gfx2_vline       ;  7  P0/P1 = x, P2/P3 = y, P4/P5 = len, A = colour
    jmp gfx2_rect        ;  8  P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h, A = colour
    jmp gfx2_frame       ;  9  P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h, A = colour
    jmp gfx2_line        ; 10  P0/P1 = x0, P2/P3 = y0, P4/P5 = x1, P6/P7 = y1, A = colour
    jmp gfx2_pattern_set ; 11  A/X = 8x8 pattern, Y = (bg << 2) | fg
    jmp gfx2_pattern_rect ; 12  P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h
    jmp gfx2_blit        ; 13  P0/P1 = x, P2/P3 = y, P4 = wbytes, P5 = h, P6/P7 = src, A = op
    jmp gfx2_blitm       ; 14  P0/P1 = x, P2/P3 = y, P4 = h, P5 = cols, P6/P7 = src

; --- text --------------------------------------------------------
    jmp font_set         ; 15  A/X = CXF image -> carry set if bad
    jmp font_style       ; 16  A = CX_BOLD | CX_UNDER
    jmp font_measure     ; 17  A/X = string -> P0/P1 = width
    jmp font_draw        ; 18  P0/P1 = x, P2/P3 = y, A/X = string -> P0/P1 = pen

; --- events ------------------------------------------------------
    jmp ev_handlers      ; 19  A/X = a table of CX_EV_COUNT vectors
    jmp ev_mainloop      ; 20  never returns
    jmp ev_dispatch      ; 21  dispatch one event and return
    jmp ev_get           ; 22  -> P0..P7 = a record; carry set if none
    jmp ev_post          ; 23  P0..P7 = a record
    jmp ev_count         ; 24  -> A = records waiting
    jmp ev_timer         ; 25  A = frames between EV_TIMERs (0 = off)
    jmp ev_frames        ; 26  -> A = the frame counter

; --- dirty rectangles --------------------------------------------
    jmp dr_reset         ; 27  -
    jmp dr_add           ; 28  P0/P1 = x, P2/P3 = y, P4/P5 = w, P6/P7 = h
    jmp dr_count         ; 29  -> A = rects
    jmp dr_get           ; 30  A = index -> P0/P1 = x0, P2/P3 = y0, P4/P5 = x1, P6/P7 = y1

; --- the loader --------------------------------------------------
    jmp cxl_load         ; 31  A/X = filename, Y = length; returns only on failure: carry, A = 1 not an app / 2 needs a newer kernel

; --- events, continued -------------------------------------------
    jmp ev_init          ; 32  clear the queue and hook the raster; an app calls this before cx_ev_handlers

; --- menus -------------------------------------------------------
    jmp cx_do_menu_set   ; 33  A/X = the menu bar (docs/formats.md); draws it, owns the top strip; carry = region stack full
    jmp cx_do_menu_off   ; 34  forget the menu; only with no menu open

; --- the pointer -------------------------------------------------
    jmp cx_do_mouse_show ; 35  A = the pointer number (1 = the arrow), or $FF to show without setting one; the loader hides it between apps, so an app that wants it asks
    jmp mouse_hide       ; 36  -

; --- themes and dialogs ------------------------------------------
    jmp cx_do_theme_set  ; 37  A/X = a 12-byte theme record (docs/formats.md): four palette RGBs plus the role indices; the palette changes instantly
    jmp cx_do_dlg_alert  ; 38  A/X = a dialog descriptor (docs/formats.md); SYNCHRONOUS -- returns A = the chosen button. RETURN picks button 0

; --- widgets -----------------------------------------------------
    jmp cx_do_wg_set     ; 39  A/X = a widget list (docs/formats.md); draws it, routes its clicks; posts EV_WIDGET(detail = index, P2 = value)
    jmp cx_do_wg_draw    ; 40  redraw the current widget list

; --- keyboard menu nav -------------------------------------------
    jmp cx_do_menu_key   ; 41  A = a key; drives the menu bar (DOWN opens, arrows move, RETURN picks, ESC dismisses). Carry set if it was a menu key. Call it from your EV_KEY handler

.popseg

