; ca65 -- GENERATED by abi/gen_bindings.py. Do not edit.
; =====================================================================
; CXRF cc65 crossing -- the parameter-block bridge for a cc65 C app
; =====================================================================
; cc65's cx16 runtime zero page starts at $22 -- exactly the CXRF
; parameter block (X16_P0..P7 = $22..$29). So a cc65 app cannot use the
; block in place; cx_run() saves cc65's whole runtime ZP, lays the mirror
; across the real block, calls the slot, reads A/X/carry and the block
; back, then restores cc65's ZP. The same shape as the llvm-mos shim --
; in asm, because cc65's inline asm is too limited to carry it.
;
; The mirror (cx_p, cx_a, ...) lives here; the C header declares it
; extern. cc65 mangles the C name `cx_p` to the asm label `_cx_p`.
; =====================================================================

.export _cx_run
.export _cx_p, _cx_a, _cx_x, _cx_y, _cx_c, _cx_slot

CXZP    = $22              ; cc65's runtime ZP base = the CXRF block base
CXZPLEN = 26              ; cc65 zpspace (sp/sreg/regsave/ptr1-4/tmp1-4/regbank)

.bss
_cx_p:      .res 8
_cx_a:      .res 1
_cx_x:      .res 1
_cx_y:      .res 1
_cx_c:      .res 1
_cx_slot:   .res 2
cx_zpsave:  .res CXZPLEN

.code
_cx_run:
    ldx #CXZPLEN-1          ; save cc65's runtime ZP out of harm's way
@sv:
    lda CXZP,x
    sta cx_zpsave,x
    dex
    bpl @sv
    ldx #7                  ; the mirror -> the real block $22..$29
@in:
    lda _cx_p,x
    sta CXZP,x
    dex
    bpl @in
    ldy _cx_y              ; A/X/Y in
    ldx _cx_x
    lda _cx_a
    jsr @slot
    sta _cx_a             ; A, X and the carry back out
    stx _cx_x
    php
    pla
    and #1
    sta _cx_c
    ldx #7                  ; the block back into the mirror
@out:
    lda CXZP,x
    sta _cx_p,x
    dex
    bpl @out
    ldx #CXZPLEN-1          ; restore cc65's runtime ZP
@rs:
    lda cx_zpsave,x
    sta CXZP,x
    dex
    bpl @rs
    rts
@slot:
    jmp (_cx_slot)          ; _cx_slot HOLDS the slot address; jump to it
