#!/usr/bin/env python3
"""charset2bdf.py -- the X16 ROM's ISO charset as a proportional BDF.

CXGEOS needs a system font it is allowed to ship. The X16 ROM's ISO
charset (PXLfont) is public domain -- x16-rom's LICENSE.md lists it
under "Public Domain" alongside the PETSCII charset and the keymaps --
and it already looks like the machine, which no imported font does.

The ROM draws it on a fixed 8x8 grid. Nearly every glyph leaves columns
blank on one side or both: `i` inks two columns, `m` inks seven. Trimming
those blanks is the whole conversion -- the glyph bitmaps are untouched,
they just stop being padded to a monospace cell, and the result is a
genuinely proportional font at no cost in either quality or licensing.

BDF is the output because that is what tools/fontconv.py reads, and what
anyone replacing this font would export. Run this once per ROM release;
the .bdf it makes is committed, so a CXGEOS build never needs the ROM
sources present.

    python tools/charset2bdf.py <x16-rom>/charset/iso-8859-15.s fonts/pxl8.bdf

Rows 0-6 sit above the baseline and row 7 below it, which is where this
font puts the descenders of g/p/q/y -- hence ascent 7, descent 1.
"""
import argparse
import re
import sys

FIRST = 0x20            # space
LAST = 0x7E             # tilde
CELL_H = 8
CELL_W = 8
ASCENT = 7              # rows 0-6 above the baseline...
DESCENT = 1             # ...row 7 below it
SPACE_WIDTH = 3         # blank glyphs have no ink to measure

BYTE_RE = re.compile(r"^\s*\.byte\s+%([01]{8})\s*(?:;.*)?$")


def read_charset(path):
    """The .s file's `.byte %........` lines, in order. 1 = ink, MSB left."""
    rows = []
    with open(path, encoding="latin-1") as f:
        for line in f:
            m = BYTE_RE.match(line)
            if m:
                rows.append(int(m.group(1), 2))
    if len(rows) < (LAST + 1) * CELL_H:
        sys.exit("%s: only %d rows; need %d for codes up to $%02X"
                 % (path, len(rows), (LAST + 1) * CELL_H, LAST))
    return rows


def trim(cell):
    """(shifted rows, width). Blank cells become a SPACE_WIDTH gap."""
    ink = [c for c in range(CELL_W)
           if any(row >> (CELL_W - 1 - c) & 1 for row in cell)]
    if not ink:
        return [0] * CELL_H, SPACE_WIDTH
    left, right = ink[0], ink[-1]
    return [(row << left) & 0xFF for row in cell], right - left + 1


def emit_bdf(rows, name):
    glyphs = []
    for code in range(FIRST, LAST + 1):
        cell = rows[code * CELL_H:(code + 1) * CELL_H]
        bits, width = trim(cell)
        glyphs.append((code, bits, width))

    maxw = max(g[2] for g in glyphs)
    out = []
    out.append("STARTFONT 2.1")
    out.append("COMMENT The X16 ROM's ISO charset (PXLfont), public domain,")
    out.append("COMMENT made proportional by trimming each glyph's blank")
    out.append("COMMENT columns. Generated by tools/charset2bdf.py -- see")
    out.append("COMMENT there for provenance. Do not hand-edit.")
    out.append("FONT -cxgeos-%s-medium-r-normal--8-80-72-72-p-%d-iso8859-15"
               % (name, maxw))
    out.append("SIZE 8 72 72")
    out.append("FONTBOUNDINGBOX %d %d 0 %d" % (maxw, CELL_H, -DESCENT))
    out.append("STARTPROPERTIES 4")
    out.append("FONT_ASCENT %d" % ASCENT)
    out.append("FONT_DESCENT %d" % DESCENT)
    out.append("DEFAULT_CHAR %d" % FIRST)
    out.append('COPYRIGHT "public domain"')
    out.append("ENDPROPERTIES")
    out.append("CHARS %d" % len(glyphs))

    for code, bits, width in glyphs:
        out.append("STARTCHAR U+%04X" % code)
        out.append("ENCODING %d" % code)
        out.append("SWIDTH %d 0" % (width * 1000 // 8))
        out.append("DWIDTH %d 0" % width)
        # The bitmap keeps the full 8-row cell: its bottom row is the
        # descender row, so the bbox sits DESCENT below the baseline.
        out.append("BBX %d %d 0 %d" % (width, CELL_H, -DESCENT))
        out.append("BITMAP")
        for row in bits:
            out.append("%02X" % row)
        out.append("ENDCHAR")

    out.append("ENDFONT")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("charset_s", help="x16-rom charset/iso-8859-15.s")
    ap.add_argument("out_bdf")
    ap.add_argument("--name", default="pxl8", help="font family name")
    args = ap.parse_args()

    rows = read_charset(args.charset_s)
    bdf = emit_bdf(rows, args.name)
    with open(args.out_bdf, "w", encoding="ascii", newline="\n") as f:
        f.write(bdf)

    widths = {}
    for code in range(FIRST, LAST + 1):
        _, w = trim(rows[code * CELL_H:(code + 1) * CELL_H])
        widths[code] = w
    print("%s: %d glyphs, widths %d-%d, avg %.1f"
          % (args.out_bdf, LAST - FIRST + 1, min(widths.values()),
             max(widths.values()), sum(widths.values()) / len(widths)))


if __name__ == "__main__":
    main()
