#!/usr/bin/env python3
"""asmsdk.py -- generate the friendly cxm_* macro layer, per assembler.

The low-level bindings (sdk/include_<dialect>/cxrf.inc) are pure address
equates and are generated by gen_bindings.py. This module is the SECOND,
friendlier layer: the cxm_* one-line macros and the descriptor builders that
today live hand-written in asmsdk/ca65/cxrf.inc.

There is ONE dialect-neutral spec here (CONSTS, FUNCS, CALLS, BUILDERS) and a
small per-dialect syntax table (DIALECTS). gen(dialect) renders the spec through
that dialect's syntax, so a new assembler is a syntax-table row, not a hand port.

Fidelity gate: the spec's ca65 rendering expands to the SAME machine code as the
committed hand-written asmsdk/ca65/cxrf.inc -- proven by assembling the app
suite with each and diffing the binaries (build.ps1 -Test). "Byte-identical"
means the expansion, exactly as the project has always meant it.

An op in a CALL's op-list is (op, target, arg):
    pw  Pn  v   -> a 16-bit store into the P-block word at X16_Pn  (_cx_pw)
    pb  Pn  v   -> lda #(v)  / sta X16_Pn        (a byte into a P-block byte)
    pl  Pn  v   -> lda #<(v) / sta X16_Pn        (pointer low  into a P byte)
    ph  Pn  v   -> lda #>(v) / sta X16_Pn        (pointer high into a P byte)
    pk  Pn  v   -> lda #^(v) / sta X16_Pn        (pointer bank into a P byte)
    a   -   v   -> lda #(v)          x  - v -> ldx #(v)     y  - v -> ldy #(v)
    al  -   v   -> lda #<(v)         xh - v -> ldx #>(v)    yh - v -> ldy #>(v)
`tail` is 'jsr' or 'jmp'; the slot label is cx_<name> unless `call` overrides it.
"""
import re

INDENT = "    "

# =====================================================================
# per-dialect syntax
# =====================================================================
# A dialect is a dict of the handful of things assemblers disagree on. The
# renderer never hard-codes ca65/64tass anywhere else.
DIALECTS = {
    "ca65": {
        "header":   "; ca65",
        "com":      ";",
        "mac_open": lambda name, ps: ".macro %s%s" % (name, (" " + ", ".join(ps)) if ps else ""),
        "mac_end":  ".endmacro",
        "invoke":   lambda name, args: "%s%s %s" % (INDENT, name, ", ".join(args)),
        "paramref": lambda n, i: n,     # a macro parameter is used bare
        "pwname":   "_cx_pw",           # the 16-bit-store helper's name
        "func_note": None,
        "byte":     ".byte",
        "word":     ".word",
        "addr":     ".addr",
        "bank_imm": lambda v: "lda #^(%s)" % v,     # ca65 has the ^ bank operator
        # the 16-bit store helper, emitted once; the stz-for-zero-high-byte
        # form the hand file uses, so the ca65 expansion stays byte-identical
        "cxpw": (
            ".macro _cx_pw addr, v\n"
            "    lda #<(v)\n"
            "    sta addr\n"
            "    .if .const(v)\n"
            "        .if (>(v)) = 0\n"
            "            stz addr+1\n"
            "        .else\n"
            "            lda #>(v)\n"
            "            sta addr+1\n"
            "        .endif\n"
            "    .else\n"
            "        lda #>(v)\n"
            "        sta addr+1\n"
            "    .endif\n"
            ".endmacro\n"
        ),
        "guard_open":  ".ifndef CXRF_ASMSDK\nCXRF_ASMSDK = 1\n",
        "guard_close": ".endif ; CXRF_ASMSDK",
        "include":  lambda p: '.include "%s"' % p,
        "func":     lambda name, ps, body: ".define %s(%s)   %s" % (name, ", ".join(ps), body),
        "equ":      lambda name, val: "%s = %s" % (name, val),
    },
    "64tass": {
        "header":   "; 64tass",
        "com":      ";",
        "mac_open": lambda name, ps: "%s .macro%s" % (name, (" " + ", ".join(ps)) if ps else ""),
        "mac_end":  ".endm",
        "invoke":   lambda name, args: "%s#%s %s" % (INDENT, name, ", ".join(args)),
        "paramref": lambda n, i: "\\" + n,   # a macro parameter is \name
        # 64tass treats a leading '_' as a LOCAL label, so the helper cannot be
        # named _cx_pw (it would be invisible where a cxm_ macro invokes it)
        "pwname":   "cxpw16",
        "func_note": None,
        "byte":     ".byte",
        "word":     ".word",
        "addr":     ".word",            # 64tass has no .addr
        "bank_imm": lambda v: "lda #((%s >> 16) & $FF)" % v,   # no ^ operator
        "cxpw": (
            "cxpw16 .macro addr, v\n"
            "    lda #<(\\v)\n"
            "    sta \\addr\n"
            "    lda #>(\\v)\n"
            "    sta \\addr+1\n"
            ".endm\n"
        ),
        "guard_open":  "",              # include-once is the caller's job in 64tass
        "guard_close": "",
        "include":  lambda p: '.include "%s"' % p,
        "func":     lambda name, ps, body: "%s .function %s\n    .endf %s" % (name, ", ".join(ps), body),
        "equ":      lambda name, val: "%s = %s" % (name, val),
    },
    # -----------------------------------------------------------------
    # ACME: !macro name .p { } ; invoke +name; params .p; data !byte/!word
    # -----------------------------------------------------------------
    "acme": {
        "header":   ";ACME",
        "com":      ";",
        "mac_open": lambda name, ps: "!macro %s%s {" % (name, (" " + ", ".join("." + p for p in ps)) if ps else ""),
        "mac_end":  "}",
        "invoke":   lambda name, args: "%s+%s %s" % (INDENT, name, ", ".join(args)),
        "paramref": lambda n, i: "." + n,
        "pwname":   "cxpw16",
        "byte":     "!byte",
        "word":     "!word",
        "addr":     "!word",            # ACME has no !addr
        "bank_imm": lambda v: "lda #((%s >> 16) & $FF)" % v,
        "cxpw": (
            "!macro cxpw16 .addr, .v {\n"
            "    lda #<(.v)\n"
            "    sta .addr\n"
            "    lda #>(.v)\n"
            "    sta .addr+1\n"
            "}\n"
        ),
        "guard_open":  "",
        "guard_close": "",
        "include":  lambda p: '!source "%s"' % p,
        "func":     None,               # ACME has no value-returning macro
        "func_note": "no value-macro in ACME; inline the expression",
        "equ":      lambda name, val: "%s = %s" % (name, val),
    },
    # -----------------------------------------------------------------
    # dasm: MAC name / ENDM ; positional {1}.. ; invoke name; data dc.b/dc.w
    # -----------------------------------------------------------------
    "dasm": {
        "header":   "; dasm",
        "com":      ";",
        "mac_open": lambda name, ps: "    MAC %s" % name,   # params are positional
        "mac_end":  "    ENDM",
        "invoke":   lambda name, args: "%s%s %s" % (INDENT, name, ", ".join(args)),
        "paramref": lambda n, i: "{%d}" % i,
        "pwname":   "cxpw16",
        "byte":     "dc.b",
        "word":     "dc.w",
        "addr":     "dc.w",
        "bank_imm": lambda v: "lda #((%s >> 16) & $FF)" % v,
        "cxpw": (
            "    MAC cxpw16\n"
            "    lda #<({2})\n"
            "    sta {1}\n"
            "    lda #>({2})\n"
            "    sta {1}+1\n"
            "    ENDM\n"
        ),
        "guard_open":  "",
        "guard_close": "",
        "include":  lambda p: '    include "%s"' % p,
        "func":     None,
        "func_note": "no value-macro in dasm; inline the expression",
        "equ":      lambda name, val: "%s = %s" % (name, val),
    },
    # -----------------------------------------------------------------
    # MADS: .macro name p / .endm ; params :p ; invoke name; data .byte/.word
    # -----------------------------------------------------------------
    "mads": {
        "header":   "; MADS",
        "com":      ";",
        "mac_open": lambda name, ps: ".macro %s%s" % (name, (" " + " ".join(ps)) if ps else ""),
        "mac_end":  ".endm",
        "invoke":   lambda name, args: "%s%s %s" % (INDENT, name, ", ".join(args)),
        "paramref": lambda n, i: ":" + n,
        "pwname":   "cxpw16",
        "byte":     ".byte",
        "word":     ".word",
        "addr":     ".word",
        "bank_imm": lambda v: "lda #((%s >> 16) & $FF)" % v,
        "cxpw": (
            ".macro cxpw16 addr v\n"
            "    lda #<(:v)\n"
            "    sta :addr\n"
            "    lda #>(:v)\n"
            "    sta :addr+1\n"
            ".endm\n"
        ),
        "guard_open":  "",
        "guard_close": "",
        "include":  lambda p: '    icl "%s"' % p,
        "func":     None,
        "func_note": "no value-macro in MADS; inline the expression",
        # MADS parses a leading '(' in a data operand as indirect addressing,
        # so grouping in a .byte/.word expression is [ ] (only the builders
        # have such expressions; the immediates keep their () fine)
        "grp_open":  "[",
        "grp_close": "]",
        "equ":      lambda name, val: "%s = %s" % (name, val),
    },
    # -----------------------------------------------------------------
    # vasm oldstyle: macro name / endm ; positional \1.. ; data byte/word
    # -----------------------------------------------------------------
    "vasm": {
        "header":   "; vasm oldstyle",
        "com":      ";",
        "mac_open": lambda name, ps: "    macro %s" % name,   # params are positional
        "mac_end":  "    endm",
        "invoke":   lambda name, args: "%s%s %s" % (INDENT, name, ", ".join(args)),
        "paramref": lambda n, i: "\\%d" % i,
        "pwname":   "cxpw16",
        "byte":     "byte",
        "word":     "word",
        "addr":     "word",
        "bank_imm": lambda v: "lda #((%s >> 16) & $FF)" % v,
        "cxpw": (
            "    macro cxpw16\n"
            "    lda #<(\\2)\n"
            "    sta \\1\n"
            "    lda #>(\\2)\n"
            "    sta \\1+1\n"
            "    endm\n"
        ),
        "guard_open":  "",
        "guard_close": "",
        "include":  lambda p: '    include "%s"' % p,
        "func":     None,
        "func_note": "no value-macro in vasm; inline the expression",
        "equ":      lambda name, val: "%s = %s" % (name, val),
    },
    # -----------------------------------------------------------------
    # KickAssembler: .macro name(p) { } ; invoke name(args); // comments;
    # .const / .label / .function ; #import ; data .byte/.word
    # -----------------------------------------------------------------
    "kick": {
        "header":   "// KickAssembler",
        "com":      "//",
        "mac_open": lambda name, ps: ".macro %s(%s) {" % (name, ", ".join(ps)),
        "mac_end":  "}",
        "invoke":   lambda name, args: "%s%s(%s)" % (INDENT, name, ", ".join(args)),
        "paramref": lambda n, i: n,     # bare, but calls use name(args)
        "pwname":   "cxpw16",
        "byte":     ".byte",
        "word":     ".word",
        "addr":     ".word",
        "bank_imm": lambda v: "lda #((%s >> 16) & $FF)" % v,
        "cxpw": (
            ".macro cxpw16(addr, v) {\n"
            "    lda #<(v)\n"
            "    sta addr\n"
            "    lda #>(v)\n"
            "    sta addr+1\n"
            "}\n"
        ),
        "guard_open":  "#importonce",
        "guard_close": "",
        "include":  lambda p: '#import "%s"' % p,
        "func":     lambda name, ps, body: ".function %s(%s) { .return %s }" % (name, ", ".join(ps), body),
        "func_note": None,
        "equ":      lambda name, val: ".const %s = %s" % (name, val),
    },
}

# =====================================================================
# the shared constants (mirror csdk/cxsdk.h; value is all that matters)
# =====================================================================
# groups of (name, value, comment); a None entry is a blank line
CONSTS = [
    ("graphics modes (cxm_gfx_mode)", [
        ("CX_MODE_GUI", "0", "640x480, 4 colours -- the desktop"),
        ("CX_MODE_BMP8", "1", "320x240, 256 colours"),
        ("CX_MODE_TILE", "2", "two tile layers + sprites (games)"),
        ("CX_MODE_TEXT", "3", "80x60 text cells, 16 colours"),
    ]),
    ("event types (an event record's byte 0 / P0)", [
        ("CX_ET_NULL", "0", ""), ("CX_ET_MOVE", "1", ""), ("CX_ET_DOWN", "2", ""),
        ("CX_ET_UP", "3", ""), ("CX_ET_DBL", "4", ""), ("CX_ET_KEY", "5", ""),
        ("CX_ET_TIMER", "6", ""), ("CX_ET_MENU", "7", ""), ("CX_ET_WIDGET", "8", ""),
        ("CX_ET_JOY", "9", ""), ("CX_ET_COUNT", "10", "handler tables are ALWAYS this many vectors"),
    ]),
    ("widget types (a record's WG_TYPE)", [
        ("CX_WG_BUTTON", "0", ""), ("CX_WG_CHECK", "1", ""), ("CX_WG_RADIO", "2", ""),
        ("CX_WG_SCROLL", "3", ""), ("CX_WG_FIELD", "4", ""), ("CX_WG_LIST", "5", ""),
        ("CX_WG_ICON", "6", "a 24x24 icon tile; WG_VAL = the icon id"),
        ("CX_WG_HIT", "7", "an invisible hit region the app draws itself"),
        ("CX_WG_SIZE", "16", "one widget record is exactly this many bytes"),
    ]),
    ("CX_WG_HIT shapes (WG_VAL) and triggers (WG_GRP)", [
        ("CX_WH_RECT", "0", ""), ("CX_WH_CIRCLE", "1", "inscribed in the box"),
        ("CX_WH_ELLIPSE", "2", ""),
        ("CX_WH_POLYGON", "3", "a regular n-gon (square box); cxm_wg_hit_poly"),
        ("CX_WH_PIE", "4", "an arc/pie wedge (square box); cxm_wg_hit_pie"),
        ("CX_WH_CLICK", "1", ""), ("CX_WH_RELEASE", "2", ""), ("CX_WH_HOVER", "4", ""),
    ]),
    ("icon ids (cxm_icon / a WG_ICON record's WG_VAL)", [
        ("CX_ICON_UP", "0", ""), ("CX_ICON_FOLDER", "1", ""), ("CX_ICON_APP", "2", ""),
        ("CX_ICON_FONT", "3", ""), ("CX_ICON_ACCESSORY", "4", ""), ("CX_ICON_DATA", "5", ""),
        ("CX_ICON_IMAGE", "6", ""), ("CX_ICON_DISK", "7", ""),
        # ids 8-17 are the desktop's per-app icons (calc, paint, game, text,
        # sound, sprite, tile, term, gears, globe); cx_icon draws them by
        # number -- see the filer's ICON_* and tools/icongen.py.
    ]),
    ("font style flags (cxm_font_style)", [
        ("CX_BOLD", "1", ""), ("CX_UNDER", "2", ""),
    ]),
    ("theme role colours (palette indices, not RGB)", [
        ("CX_PAPER", "0", "the background"),
        ("CX_HI", "1", "the highlight fill"),
        ("CX_FRAME", "3", "borders"),
    ]),
    ("keys (PETSCII), as EV_KEY delivers them", [
        ("CX_K_ENTER", "$0D", ""), ("CX_K_ESC", "$1B", ""), ("CX_K_TAB", "$09", ""),
        ("CX_K_BTAB", "$18", "shift-TAB"), ("CX_K_DEL", "$14", ""), ("CX_K_UP", "$91", ""),
        ("CX_K_DOWN", "$11", ""), ("CX_K_LEFT", "$9D", ""), ("CX_K_RIGHT", "$1D", ""),
        ("CX_K_SPACE", "$20", ""),
    ]),
    ("audio: PSG waveforms and panning", [
        ("CX_WAVE_PULSE", "$00", ""), ("CX_WAVE_SAW", "$40", ""), ("CX_WAVE_TRI", "$80", ""),
        ("CX_WAVE_NOISE", "$C0", ""), ("CX_PAN_LEFT", "$40", ""), ("CX_PAN_RIGHT", "$80", ""),
        ("CX_PAN_BOTH", "$C0", ""),
    ]),
    ("PCM format bits (cxm_pcm_ctrl); low nibble is volume 0-15", [
        ("CX_PCM_16BIT", "$20", ""), ("CX_PCM_STEREO", "$10", ""),
    ]),
    ("joystick buttons (ACTIVE HIGH: pressed = 1)", [
        ("CX_J_RIGHT", "$0001", ""), ("CX_J_LEFT", "$0002", ""), ("CX_J_DOWN", "$0004", ""),
        ("CX_J_UP", "$0008", ""), ("CX_J_START", "$0010", ""), ("CX_J_SELECT", "$0020", ""),
        ("CX_J_Y", "$0040", ""), ("CX_J_B", "$0080", ""), ("CX_J_R", "$1000", ""),
        ("CX_J_L", "$2000", ""), ("CX_J_X", "$4000", ""), ("CX_J_A", "$8000", ""),
    ]),
    ("sprites", [
        ("CX_SPR_4BPP", "$00", "image colour depth (cxm_sprite_image)"),
        ("CX_SPR_8BPP", "$80", ""),
        ("CX_SPR_8", "0", "size codes (cxm_sprite_size)"),
        ("CX_SPR_16", "1", ""), ("CX_SPR_32", "2", ""), ("CX_SPR_64", "3", ""),
        ("CX_SPR_HIDE", "$00", "Z-depths (cxm_sprite_z / _flags)"),
        ("CX_SPR_BEHIND", "$04", ""), ("CX_SPR_MIDDLE", "$08", ""), ("CX_SPR_FRONT", "$0C", ""),
        ("CX_SPR_HFLIP", "$01", ""), ("CX_SPR_VFLIP", "$02", ""),
        ("CX_SPR_VRAM", "$1E000", "the 4KB VRAM region for app sprite images"),
    ]),
    ("tiles (CX_MODE_TILE)", [
        ("CX_TILE_IMG", "$00000", "tile pixel data (up to 1024 tiles)"),
        ("CX_CELL_HF", "$0400", "cell attribute bits"),
        ("CX_CELL_VF", "$0800", ""),
    ]),
    ("immediate widget-painter metrics (match the kernel toolkit)", [
        ("CX_FONT_H", "8", "the system font's glyph height"),
        ("CX_BOX", "12", "the checkbox marker square (= WG_BOX)"),
        ("CX_THUMB", "16", "the slider thumb width (= WG_THUMB)"),
        ("CX_SLIDER_H", "16", "the slider's height"),
    ]),
    ("event source mask (cxm_ev_mask)", [
        ("CX_EVS_MOUSE", "1", ""), ("CX_EVS_KEYS", "2", ""), ("CX_EVS_SPRCOL", "4", ""),
    ]),
]

# function-like packers (name, params, body-expression, comment)
FUNCS = [
    ("CX_YM", ["octave", "note"], "((((octave) & 7) << 4) | ((note) & $0F))",
     "pack an octave (0-7) and a note (1-12) into a cxm_ym_note code"),
    ("CX_CELL", ["idx", "pal"], "(((idx) & $3FF) | ((pal) << 12))",
     "pack a tile index (0-1023) and palette (0-15) into a cell word"),
]

# =====================================================================
# the call macros (one per ABI slot, plus the say/font_draw pair)
# =====================================================================
# (name, params, comment, ops, tail[, call_override])
CALLS = [
    # --- system ---
    ("version", [], "-> A/X = ABI version", [], "jsr"),
    ("exit", [], "never returns: back to the shell", [], "jmp"),
    # --- screen / graphics (same calls in every mode) ---
    ("gfx_init", [], "= mode GUI, fresh desktop canvas", [], "jsr"),
    ("gfx_clear", ["col"], "fill the canvas with a colour", [("a", None, "col")], "jsr"),
    ("gfx_mode", ["m"], "switch mode -> carry set if unknown", [("a", None, "m")], "jsr"),
    ("gfx_info", [], "-> A=mode, P0/1=w, P2/3=h, P4=bpp, P5/6=stride", [], "jsr"),
    ("gfx_pset", ["x0", "y0", "col"], "",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("a", None, "col")], "jsr"),
    ("gfx_read", ["x0", "y0"], "-> A = colour, $FF off screen",
     [("pw", "P0", "x0"), ("pw", "P2", "y0")], "jsr"),
    ("gfx_hline", ["x0", "y0", "len", "col"], "",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("pw", "P4", "len"), ("a", None, "col")], "jsr"),
    ("gfx_vline", ["x0", "y0", "len", "col"], "",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("pw", "P4", "len"), ("a", None, "col")], "jsr"),
    ("gfx_rect", ["x0", "y0", "w0", "h0", "col"], "",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("pw", "P4", "w0"), ("pw", "P6", "h0"), ("a", None, "col")], "jsr"),
    ("gfx_frame", ["x0", "y0", "w0", "h0", "col"], "",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("pw", "P4", "w0"), ("pw", "P6", "h0"), ("a", None, "col")], "jsr"),
    ("gfx_line", ["x0", "y0", "x1", "y1", "col"], "",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("pw", "P4", "x1"), ("pw", "P6", "y1"), ("a", None, "col")], "jsr"),
    ("gfx_pattern", ["pat", "bg", "fg"], "A/X = 8x8 pattern, Y = (bg<<2)|fg",
     [("y", None, "(((bg) & 3) << 2) | ((fg) & 3)"), ("al", None, "pat"), ("xh", None, "pat")], "jsr"),
    ("gfx_patrect", ["x0", "y0", "w0", "h0"], "",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("pw", "P4", "w0"), ("pw", "P6", "h0")], "jsr"),
    ("gfx_blit", ["x0", "y0", "wbytes", "h0", "src", "op"], "",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("pb", "P4", "wbytes"), ("pb", "P5", "h0"),
      ("pw", "P6", "src"), ("a", None, "op")], "jsr"),
    ("gfx_blitm", ["x0", "y0", "h0", "cols", "src"], "",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("pb", "P4", "h0"), ("pb", "P5", "cols"),
      ("pw", "P6", "src")], "jsr"),
    ("gfx_circle", ["xc", "yc", "rad", "col"], "",
     [("pw", "P0", "xc"), ("pw", "P2", "yc"), ("pb", "P4", "rad"), ("a", None, "col")], "jsr"),
    ("gfx_disc", ["xc", "yc", "rad", "col"], "",
     [("pw", "P0", "xc"), ("pw", "P2", "yc"), ("pb", "P4", "rad"), ("a", None, "col")], "jsr"),
    ("gfx_ellipse", ["xc", "yc", "rx", "ry", "col"], "",
     [("pw", "P0", "xc"), ("pw", "P2", "yc"), ("pb", "P4", "rx"), ("pb", "P5", "ry"), ("a", None, "col")], "jsr"),
    ("gfx_fellipse", ["xc", "yc", "rx", "ry", "col"], "",
     [("pw", "P0", "xc"), ("pw", "P2", "yc"), ("pb", "P4", "rx"), ("pb", "P5", "ry"), ("a", None, "col")], "jsr"),
    ("gfx_flood", ["x0", "y0", "col"], "-> carry set if the seed stack overflowed",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("a", None, "col")], "jsr"),
    ("gfx_shape", ["kind", "xc", "yc", "rad", "p5", "p6", "col"],
     "one dispatched slot; kind 0 polygon, 1 fpolygon, 2 arc, 3 pie. "
     "polygon: p5 = sides, p6 = rotation; arc/pie: p5 = start, p6 = end",
     [("x", None, "kind"), ("pw", "P0", "xc"), ("pw", "P2", "yc"),
      ("pb", "P4", "rad"), ("pb", "P5", "p5"), ("pb", "P6", "p6"), ("a", None, "col")], "jsr"),
    ("icon", ["id", "x0", "y0"], "a built-in 24x24 icon (modes 0/1)",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("a", None, "id")], "jsr"),
    # --- palette ---
    ("pal_set", ["index", "rgb"], "one entry; rgb is 12-bit $0RGB",
     [("yh", None, "rgb"), ("x", None, "index"), ("al", None, "rgb")], "jsr"),
    ("pal_load", ["src", "first", "count"], "bulk-load entries from RAM",
     [("pw", "P0", "src"), ("x", None, "count"), ("a", None, "first")], "jsr"),
    # --- text ---
    ("font_set", ["cxf"], "adopt a .CXF -> carry set if bad",
     [("al", None, "cxf"), ("xh", None, "cxf")], "jsr"),
    ("font_style", ["flags"], "CX_BOLD | CX_UNDER", [("a", None, "flags")], "jsr"),
    ("font_measure", ["str"], "-> P0/1 = pixel width",
     [("al", None, "str"), ("xh", None, "str")], "jsr"),
    ("say", ["str", "x0", "y0"], "draw at (x0,y0) -> P0/1 = pen x",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("al", None, "str"), ("xh", None, "str")], "jsr", "cx_font_draw"),
    ("ink", ["col"], "text ink for the CURRENT mode", [("a", None, "col")], "jsr"),
    # --- tiles ---
    ("tile_setup", ["layer", "bpp"], "bpp 2/4/8; -> carry set outside mode 2",
     [("x", None, "bpp"), ("a", None, "layer")], "jsr"),
    ("tile_scroll", ["layer", "hscroll", "vscroll"], "",
     [("pw", "P0", "hscroll"), ("pw", "P2", "vscroll"), ("a", None, "layer")], "jsr"),
    ("tile_cell", ["layer", "column", "row", "cell"], "",
     [("pw", "P0", "cell"), ("x", None, "column"), ("y", None, "row"), ("a", None, "layer")], "jsr"),
    ("tile_fill", ["layer", "cell"], "",
     [("pw", "P0", "cell"), ("a", None, "layer")], "jsr"),
    ("tile_text", ["layer", "on"], "flip a tile layer to a 1bpp text overlay and back",
     [("x", None, "on"), ("a", None, "layer")], "jsr"),
    ("vram_stream", ["vram", "vrambank", "srcbank", "count"],
     "banked RAM -> VRAM; vrambank = VRAM dst bit 16 (0/1)",
     [("pw", "P0", "vram"), ("pb", "P2", "vrambank"), ("pb", "P3", "srcbank"),
      ("pw", "P4", "count")], "jsr"),
    ("tile_dbuf", ["layer", "on"], "double-buffer a tile layer on/off",
     [("x", None, "on"), ("a", None, "layer")], "jsr"),
    ("tile_flip", ["layer"], "present the drawn buffer (waits for vblank)",
     [("a", None, "layer")], "jsr"),
    # --- events (a handler table is ALWAYS CX_ET_COUNT vectors) ---
    ("ev_init", [], "clear the queue, hook the raster", [], "jsr"),
    ("ev_handlers", ["tbl"], "A/X = CX_ET_COUNT vectors",
     [("al", None, "tbl"), ("xh", None, "tbl")], "jsr"),
    ("ev_mainloop", [], "never returns", [], "jmp"),
    ("ev_dispatch", [], "dispatch one event and return", [], "jsr"),
    ("ev_get", [], "-> P0..P7 = a record; carry if none", [], "jsr"),
    ("ev_next", [], "like ev_get, but routes mouse to the toolkit", [], "jsr"),
    ("ev_post", [], "P0..P7 = a record (fill it first)", [], "jsr"),
    ("ev_count", [], "-> A = records waiting", [], "jsr"),
    ("ev_timer", ["frames"], "A = frames between EV_TIMERs (0 = off)", [("a", None, "frames")], "jsr"),
    ("ev_frames", [], "-> A = the frame counter", [], "jsr"),
    ("ev_mask", ["sources"], "which sources the frame tick samples", [("a", None, "sources")], "jsr"),
    ("ev_raster", ["hdlr"], "A/X = a per-frame raster handler, or 0 to remove",
     [("al", None, "hdlr"), ("xh", None, "hdlr")], "jsr"),
    ("ev_stop", [], "return the raster line to the game's handler", [], "jsr"),
    # --- dirty rectangles ---
    ("dirty_reset", [], "", [], "jsr"),
    ("dirty_add", ["x0", "y0", "w0", "h0"], "",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("pw", "P4", "w0"), ("pw", "P6", "h0")], "jsr"),
    ("dirty_count", [], "-> A = rects", [], "jsr"),
    ("dirty_get", ["idx"], "A=index -> P0/1=x0,P2/3=y0,P4/5=x1,P6/7=y1", [("a", None, "idx")], "jsr"),
    # --- pointer, menus, widgets ---
    ("mouse_show", ["ptr"], "A = pointer number (1 = arrow), $FF = show as-is", [("a", None, "ptr")], "jsr"),
    ("mouse_hide", [], "", [], "jsr"),
    ("menu_set", ["bar"], "A/X = a menu bar -> carry = region stack full",
     [("al", None, "bar"), ("xh", None, "bar")], "jsr"),
    ("menu_off", [], "", [], "jsr"),
    ("menu_key", ["key"], "drive the menu bar -> carry = it was a menu key", [("a", None, "key")], "jsr"),
    ("menu_active", [], "-> A = 1 if a menu is open (mouse or kbd), Z set if none", [], "jsr"),
    ("wg_set", ["lst"], "A/X = a widget list; draws + routes it",
     [("al", None, "lst"), ("xh", None, "lst")], "jsr"),
    ("wg_draw", [], "redraw the current widget list", [], "jsr"),
    ("wg_key", ["key"], "drive widget focus -> carry = it was a widget key", [("a", None, "key")], "jsr"),
    # --- themes and dialogs ---
    ("theme_set", ["rec"], "A/X = a 12-byte theme record",
     [("al", None, "rec"), ("xh", None, "rec")], "jsr"),
    ("dlg_alert", ["desc"], "A/X = a dialog descriptor -> A = the button",
     [("al", None, "desc"), ("xh", None, "desc")], "jsr"),
    ("dlg_prompt", ["msg", "buf", "cap"], "modal editor -> A = length, carry = cancelled",
     [("pw", "P0", "buf"), ("pb", "P2", "cap"), ("al", None, "msg"), ("xh", None, "msg")], "jsr"),
    ("panel", ["desc"], "A/X = a panel descriptor -> A = the button",
     [("al", None, "desc"), ("xh", None, "desc")], "jsr"),
    # --- audio: PSG + YM2151 ---
    ("psg_init", [], "", [], "jsr"),
    ("psg_freq", ["voice", "freq"], "X = voice, P0/1 = frequency word",
     [("pw", "P0", "freq"), ("x", None, "voice")], "jsr"),
    ("psg_vol", ["voice", "vol", "pan"], "X = voice, A = vol (0-63), Y = pan",
     [("y", None, "pan"), ("x", None, "voice"), ("a", None, "vol")], "jsr"),
    ("psg_wave", ["voice", "wave", "pw"], "X = voice, A = waveform, Y = pulse width",
     [("y", None, "pw"), ("x", None, "voice"), ("a", None, "wave")], "jsr"),
    ("psg_off", ["voice"], "X = voice; silence, keep panning", [("x", None, "voice")], "jsr"),
    ("ym_init", [], "", [], "jsr"),
    ("ym_note", ["chan", "code"], "A = channel, X = CX_YM(octave, note); 0 releases",
     [("x", None, "code"), ("a", None, "chan")], "jsr"),
    ("ym_off", ["chan"], "", [("a", None, "chan")], "jsr"),
    ("ym_vol", ["chan", "atten"], "A = channel, X = attenuation",
     [("x", None, "atten"), ("a", None, "chan")], "jsr"),
    ("ym_patch", ["chan", "idx"], "A = channel, X = ROM patch index (0-162)",
     [("x", None, "idx"), ("a", None, "chan")], "jsr"),
    # --- PCM ---
    ("pcm_ctrl", ["ctrl"], "volume 0-15 | CX_PCM_16BIT | CX_PCM_STEREO", [("a", None, "ctrl")], "jsr"),
    ("pcm_play", ["src", "len", "rate"], "P0/1 = source, P2/3 = bytes, A = rate (1-128)",
     [("pw", "P0", "src"), ("pw", "P2", "len"), ("a", None, "rate")], "jsr"),
    ("pcm_stop", [], "", [], "jsr"),
    ("pcm_active", [], "-> A = 1 while a sample still plays", [], "jsr"),
    # --- joysticks ---
    ("joy_get", ["pad"], "A = pad -> A/X = buttons, carry = absent", [("a", None, "pad")], "jsr"),
    ("joy_enable", ["mask"], "scan pads in mask each frame, post EV_JOY", [("a", None, "mask")], "jsr"),
    # --- sprites (0 is the mouse, drive 1-127) ---
    ("sprite_image", ["spr", "addr", "mode"], "point sprite at its VRAM image",
     [("pl", "P0", "addr"), ("ph", "P1", "addr"), ("pk", "P2", "addr"), ("x", None, "spr"), ("a", None, "mode")], "jsr"),
    ("sprite_pos", ["spr", "x0", "y0"], "",
     [("pw", "P0", "x0"), ("pw", "P2", "y0"), ("x", None, "spr")], "jsr"),
    ("sprite_size", ["spr", "wcode", "hcode", "pal"], "size codes CX_SPR_8/16/32/64",
     [("pb", "P0", "pal"), ("x", None, "spr"), ("y", None, "hcode"), ("a", None, "wcode")], "jsr"),
    ("sprite_flags", ["spr", "flags"], "full write: collision<<4 | Z | flips",
     [("x", None, "spr"), ("a", None, "flags")], "jsr"),
    ("sprite_z", ["spr", "z"], "Z-depth only (CX_SPR_HIDE/BEHIND/MIDDLE/FRONT)",
     [("x", None, "spr"), ("a", None, "z")], "jsr"),
    ("spr_collide", [], "-> A = collision groups since last call", [], "jsr"),
    # --- loader and desk accessories ---
    ("app_load", ["name", "len"], "load+run a .CXA -> returns only on failure (A=reason)",
     [("y", None, "len"), ("al", None, "name"), ("xh", None, "name")], "jsr"),
    ("da_open", ["name", "len"], "open a .CXD over the running app -> carry = fail",
     [("y", None, "len"), ("al", None, "name"), ("xh", None, "name")], "jsr"),
    ("da_close", [], "", [], "jsr"),
    ("file_load", ["name", "len", "dst", "cap"], "-> carry set/A=reason, else P4/5 = bytes read",
     [("pw", "P0", "dst"), ("pw", "P2", "cap"), ("y", None, "len"), ("al", None, "name"), ("xh", None, "name")], "jsr"),
    ("vload", ["name", "len", "vaddr", "vbank", "raw"], "a file straight into VRAM",
     [("pw", "P0", "vaddr"), ("pb", "P2", "vbank"), ("pb", "P3", "raw"), ("y", None, "len"),
      ("al", None, "name"), ("xh", None, "name")], "jsr"),
    ("bload", ["name", "len", "bank", "addr", "raw"], "a file into banked RAM (bank 20+)",
     [("pb", "P0", "bank"), ("pl", "P1", "addr"), ("ph", "P2", "addr"), ("pb", "P3", "raw"),
      ("y", None, "len"), ("al", None, "name"), ("xh", None, "name")], "jsr"),
    # --- directory and DOS ---
    ("dir_open", ["pat", "len"], "open the directory channel -> carry = DOS error",
     [("y", None, "len"), ("al", None, "pat"), ("xh", None, "pat")], "jsr"),
    ("dir_next", ["buf"], "P0/1 = a >=17-byte buffer -> A=0 file/1 dir, carry=done",
     [("pw", "P0", "buf")], "jsr"),
    ("dir_close", [], "", [], "jsr"),
    ("dos_cmd", ["cmd", "len"], "A/X = a CMDR-DOS command -> A = status (>=20 = error)",
     [("y", None, "len"), ("al", None, "cmd"), ("xh", None, "cmd")], "jsr"),
    ("dos_msg", ["buf"], "P0/1 = a >=64-byte buffer -> A = reply length",
     [("pw", "P0", "buf")], "jsr"),
    # --- clipboard ---
    ("clip_put", ["type", "src", "len"], "A = type, P0/1 = src, P2/3 = len -> carry = too big",
     [("pw", "P0", "src"), ("pw", "P2", "len"), ("a", None, "type")], "jsr"),
    ("clip_get", ["dst", "cap"], "P0/1 = dst, P2/3 = cap -> A = type, P2/3 = length copied",
     [("pw", "P0", "dst"), ("pw", "P2", "cap")], "jsr"),
    ("clip_type", [], "-> A = the type waiting (0 = empty), P2/3 = length", [], "jsr"),
]

# macros that are pure aliases: (name, params, body-macro, comment)
ALIASES = [
    ("font_draw", ["str", "x0", "y0"], "cxm_say", "the 1:1 slot name; = cxm_say"),
]

# =====================================================================
# descriptor builders (data-record emitters)
# =====================================================================
# each line is (directive, [values]); directive in {byte, word, addr, raw}
# 'raw' emits the value text verbatim (for the low/high theme bytes etc.)
BUILDERS = [
    ("wg_button", ["x0", "y0", "w0", "h0", "label"], "a push button", [
        ("byte", ["CX_WG_BUTTON", "0"]), ("word", ["x0", "y0", "w0"]),
        ("byte", ["h0", "0", "0"]), ("addr", ["label"]), ("byte", ["0", "0", "0"]),
    ]),
    ("wg_check", ["x0", "y0", "w0", "h0", "on", "label"], "on = 1 checked", [
        ("byte", ["CX_WG_CHECK", "0"]), ("word", ["x0", "y0", "w0"]),
        ("byte", ["h0", "on", "0"]), ("addr", ["label"]), ("byte", ["0", "0", "0"]),
    ]),
    ("wg_radio", ["x0", "y0", "w0", "h0", "on", "group", "label"], "", [
        ("byte", ["CX_WG_RADIO", "0"]), ("word", ["x0", "y0", "w0"]),
        ("byte", ["h0", "on", "group"]), ("addr", ["label"]), ("byte", ["0", "0", "0"]),
    ]),
    ("wg_scroll", ["x0", "y0", "w0", "h0", "val", "max"], "value 0..max inclusive", [
        ("byte", ["CX_WG_SCROLL", "0"]), ("word", ["x0", "y0", "w0"]),
        ("byte", ["h0", "val", "max"]), ("addr", ["0"]), ("byte", ["0", "0", "0"]),
    ]),
    ("wg_field", ["x0", "y0", "w0", "h0", "cap", "buf"], "buf = a NUL-terminated edit buffer", [
        ("byte", ["CX_WG_FIELD", "0"]), ("word", ["x0", "y0", "w0"]),
        ("byte", ["h0", "0", "cap"]), ("addr", ["buf"]), ("byte", ["0", "0", "0"]),
    ]),
    ("wg_list", ["x0", "y0", "w0", "h0", "count", "ptrs"], "ptrs = a list of string pointers", [
        ("byte", ["CX_WG_LIST", "0"]), ("word", ["x0", "y0", "w0"]),
        ("byte", ["h0", "0", "count"]), ("addr", ["ptrs"]), ("byte", ["0", "0", "0"]),
    ]),
    ("wg_list2", ["x0", "y0", "w0", "h0", "count", "ptrs", "sizes"], "two-column list: sizes = a parallel array of size-string pointers, drawn right-aligned (null = no size that row)", [
        ("byte", ["CX_WG_LIST", "0"]), ("word", ["x0", "y0", "w0"]),
        ("byte", ["h0", "0", "count"]), ("addr", ["ptrs"]), ("byte", ["0"]), ("addr", ["sizes"]),
    ]),
    ("wg_icon", ["x0", "y0", "w0", "h0", "id", "label"], "a 24x24 icon; id = CX_ICON_*", [
        ("byte", ["CX_WG_ICON", "0"]), ("word", ["x0", "y0", "w0"]),
        ("byte", ["h0", "id", "0"]), ("addr", ["label"]), ("byte", ["0", "0", "0"]),
    ]),
    ("wg_hit", ["x0", "y0", "w0", "h0", "shape", "trig"], "an invisible hit region the app draws", [
        ("byte", ["CX_WG_HIT", "0"]), ("word", ["x0", "y0", "w0"]),
        ("byte", ["h0", "shape", "trig"]), ("addr", ["0"]), ("byte", ["0", "0", "0"]),
    ]),
    ("wg_hit_poly", ["x0", "y0", "w0", "h0", "sides", "rot", "trig"], "a hit region: a regular n-gon (square box)", [
        ("byte", ["CX_WG_HIT", "0"]), ("word", ["x0", "y0", "w0"]),
        ("byte", ["h0", "CX_WH_POLYGON", "trig"]), ("addr", ["0"]), ("byte", ["sides", "rot", "0"]),
    ]),
    ("wg_hit_pie", ["x0", "y0", "w0", "h0", "a0", "a1", "trig"], "a hit region: an arc/pie wedge (square box)", [
        ("byte", ["CX_WG_HIT", "0"]), ("word", ["x0", "y0", "w0"]),
        ("byte", ["h0", "CX_WH_PIE", "trig"]), ("addr", ["0"]), ("byte", ["a0", "a1", "0"]),
    ]),
    ("wcount", ["first", "last"], "a widget list's leading count, from the record span", [
        ("byte", ["(last - first - 1) / CX_WG_SIZE"]),
    ]),
    ("menu_bar", ["nmenus"], "a menu bar: a count, then (title, items) per menu", [
        ("byte", ["nmenus"]),
    ]),
    ("menu", ["title", "items"], "one bar entry", [
        ("addr", ["title", "items"]),
    ]),
    ("items", ["nitems"], "one menu's drop-down: a count, then a label per item", [
        ("byte", ["nitems"]),
    ]),
    ("item", ["label"], "one item / button label", [
        ("addr", ["label"]),
    ]),
    ("dialog", ["nbuttons", "msg"], "an alert descriptor; buttons follow with cxm_item", [
        ("byte", ["nbuttons"]), ("addr", ["msg"]),
    ]),
    ("panel_hdr", ["x0", "y0", "w0", "h0", "title", "wlist", "nbuttons"],
     "a modal panel header; buttons follow with cxm_item", [
        ("word", ["x0", "y0", "w0"]), ("byte", ["h0"]), ("addr", ["title"]),
        ("addr", ["wlist"]), ("byte", ["nbuttons"]),
    ]),
    ("theme_rec", ["c0", "c1", "c2", "c3", "paper", "hi", "frame"],
     "a 12-byte theme: four $0RGB colours, then paper/hi/frame roles", [
        ("raw", ["<(c0), >(c0)"]), ("raw", ["<(c1), >(c1)"]),
        ("raw", ["<(c2), >(c2)"]), ("raw", ["<(c3), >(c3)"]),
        ("byte", ["paper", "hi", "frame", "0"]),
    ]),
]


# =====================================================================
# the renderer
# =====================================================================
def _subst(d, text, params):
    """Rewrite each whole-word parameter occurrence to the dialect's reference
    form: bare (ca65/kick), prefixed (\\p 64tass, .p acme, :p mads), or
    positional ({1} dasm, \\1 vasm)."""
    pr = d["paramref"]
    for i, p in enumerate(params):
        ref = pr(p, i + 1)
        if ref == p:
            continue
        # a function replacement so a '\\' in the ref is not read as a regex escape
        text = re.sub(r"\b" + re.escape(p) + r"\b", lambda _m, r=ref: r, text)
    return text


def _op_lines(d, op, target, arg, params):
    a = _subst(d, arg, params)
    P = "X16_" + target if target else None
    if op == "pw":
        return [d["invoke"](d["pwname"], [P, a])]
    if op == "pb":
        return [INDENT + "lda #(%s)" % a, INDENT + "sta " + P]
    if op == "pl":
        return [INDENT + "lda #<(%s)" % a, INDENT + "sta " + P]
    if op == "ph":
        return [INDENT + "lda #>(%s)" % a, INDENT + "sta " + P]
    if op == "pk":
        return [INDENT + d["bank_imm"](a), INDENT + "sta " + P]
    if op == "a":
        return [INDENT + "lda #(%s)" % a]
    if op == "al":
        return [INDENT + "lda #<(%s)" % a]
    if op == "x":
        return [INDENT + "ldx #(%s)" % a]
    if op == "xh":
        return [INDENT + "ldx #>(%s)" % a]
    if op == "y":
        return [INDENT + "ldy #(%s)" % a]
    if op == "yh":
        return [INDENT + "ldy #>(%s)" % a]
    raise ValueError("unknown op %r" % op)


def _render_call(d, spec):
    name, params, comment = spec[0], spec[1], spec[2]
    ops, tail = spec[3], spec[4]
    call = spec[5] if len(spec) > 5 else "cx_" + name
    head = d["mac_open"]("cxm_" + name, params)
    if comment:
        head += "                " + d["com"] + " " + comment
    L = [head]
    for op, target, arg in ops:
        L.extend(_op_lines(d, op, target, arg, params))
    L.append(INDENT + "%s %s" % (tail, call))
    L.append(d["mac_end"])
    return "\n".join(L)


def _render_alias(d, spec):
    name, params, body, comment = spec
    head = d["mac_open"]("cxm_" + name, params)
    if comment:
        head += "                " + d["com"] + " " + comment
    inner = d["invoke"](body, [_subst(d, p, params) for p in params])
    return "\n".join([head, inner, d["mac_end"]])


def _render_builder(d, spec):
    name, params, comment, lines = spec
    head = d["mac_open"]("cxm_" + name, params)
    if comment:
        head += "                " + d["com"] + " " + comment
    go, gc = d.get("grp_open", "("), d.get("grp_close", ")")

    def grp(s):
        return s.replace("(", go).replace(")", gc) if go != "(" else s

    L = [head]
    for directive, values in lines:
        vals = ", ".join(grp(_subst(d, v, params)) for v in values)
        if directive == "raw":
            L.append(INDENT + d["byte"] + " " + vals)
        else:
            L.append(INDENT + d[directive] + " " + vals)
    L.append(d["mac_end"])
    return "\n".join(L)


def gen(dialect, version, slots):
    """Return the friendly asmsdk/<dialect>/cxrf.inc text."""
    d = DIALECTS[dialect]
    c = d["com"]
    L = [d["header"] + " -- GENERATED by abi/gen_bindings.py. Do not edit."]
    L.append(c + " =====================================================================")
    L.append(c + " CXRF asmsdk (%s) -- friendly cxm_* macros over the generated ABI" % dialect)
    L.append(c + " =====================================================================")
    L.append(c + " The low-level include (sdk/include_%s/cxrf.inc) gives the slot" % dialect)
    L.append(c + " ADDRESSES; this layer adds the named one-line cxm_* macros, the shared")
    L.append(c + " CX_* constants, and the descriptor builders -- so an app reads by intent.")
    L.append(c + " Include AFTER x16.asm (the macros use X16_P0..P7).")
    L.append(c + " =====================================================================")
    L.append("")
    if d["guard_open"]:
        L.append(d["guard_open"])
    L.append(c + " the slot addresses (cx_version = $8010, ...)")
    L.append(d["include"]("sdk/include_%s/cxrf.inc" % dialect))
    L.append("")

    # constants
    L.append(c + " =====================================================================")
    L.append(c + " constants (mirror csdk/cxsdk.h)")
    L.append(c + " =====================================================================")
    for group, items in CONSTS:
        L.append("")
        L.append(c + " --- " + group + " ---")
        for name, val, cm in items:
            line = d["equ"](name, val)
            if cm:
                line += "        " + c + " " + cm
            L.append(line)
    L.append("")
    if d["func"]:
        for name, ps, body, cm in FUNCS:
            L.append(c + " " + cm)
            L.append(d["func"](name, ps, body))
    else:
        L.append(c + " " + d["func_note"] + ":")
        for name, ps, body, cm in FUNCS:
            L.append(c + "   %s(%s) = %s" % (name, ", ".join(ps), body))
    L.append("")

    # the store helper
    L.append(c + " =====================================================================")
    L.append(c + " internal: _cx_pw stores a 16-bit value into a P-block word")
    L.append(c + " =====================================================================")
    L.append(d["cxpw"].rstrip("\n"))
    L.append("")

    # call macros
    L.append(c + " =====================================================================")
    L.append(c + " call macros -- one per ABI slot")
    L.append(c + " =====================================================================")
    for spec in CALLS:
        L.append(_render_call(d, spec))
    for spec in ALIASES:
        L.append(_render_alias(d, spec))
    L.append("")

    # descriptor builders
    L.append(c + " =====================================================================")
    L.append(c + " descriptor builders -- the byte layouts of docs/formats.md")
    L.append(c + " =====================================================================")
    for spec in BUILDERS:
        L.append(_render_builder(d, spec))

    if d["guard_close"]:
        L.append("")
        L.append(d["guard_close"])
    return "\n".join(L) + "\n"


# dialects gen_bindings.py writes into asmsdk/<dialect>/. ca65 is deliberately
# absent: its hand-written file is the reference the spec is proven against
# (build.ps1 -Test assembles the app suite with the spec's ca65 rendering and
# diffs the binaries), so it is never overwritten here.
EMIT = ["64tass", "acme", "dasm", "mads", "vasm", "kick"]


if __name__ == "__main__":
    import sys
    if len(sys.argv) != 2 or sys.argv[1] not in DIALECTS:
        sys.exit("usage: asmsdk.py <%s>" % "|".join(DIALECTS))
    sys.stdout.write(gen(sys.argv[1], 1, []))
