#!/usr/bin/env python3
"""gen_bindings.py -- abi/cxgeos.abi into a jump table and twelve bindings.

    python abi/gen_bindings.py            # generate, then check
    python abi/gen_bindings.py --selftest

An app never links kernel code. It calls a table of JMPs at a fixed
address, so one kernel serves every app in any toolchain, forever. This
generates both ends of that:

    kernel/resident/jumptab.asm   the table itself, in slot order
    sdk/include_<dialect>/cxgeos.inc   x7 assemblers
    sdk/include_<compiler>/cxgeos.h    x5 C compilers

The manifest is the only place slot numbers are decided, and they are
append-only: a slot number is a promise to every app already built. The
checks below enforce that as far as a generator can -- duplicate slots,
gaps, reordering, a `since` above the file's version -- but the rule
that a released slot never changes meaning is a human one.

The C bindings declare the parameter block, not the calls: CXGEOS
arguments go in X16_P0..P7, which C has no way to express. A C app sets
them through cx_p[] and calls the slot. For four of the compilers that
is a raw pointer to $22; for llvm-mos it cannot be -- the compiler keeps
its soft stack pointer in __rc0/__rc1 at $22/$23, so its header mirrors
the block and cx_run() carries the mirror across the real thing with
$22-$25 saved. The same per-compiler-shim idea as x16clib, arrived at
the hard way.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "abi" / "cxgeos.abi"

TABLE_ADDR = 0x8010             # the first JMP
HEADER_ADDR = 0x8000
MAGIC = "CXOS"

ASM_DIALECTS = ["acme", "ca65", "64tass", "kick", "dasm", "mads", "vasm"]
C_COMPILERS = ["cc65", "llvm", "kickc", "oscar64", "vbcc"]

ROW = re.compile(r"^(\d+)\s+(\w+)\s+(\d+)\s+(.*)$")


class AbiError(Exception):
    pass


def parse(text):
    version = None
    slots = []
    section = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line.strip():
            continue
        if line.startswith("#="):
            section = line[2:].strip()
            continue
        if line.startswith("#"):
            continue
        m = re.match(r"^version\s*=\s*(\d+)$", line.strip())
        if m:
            version = int(m.group(1))
            continue
        m = ROW.match(line.strip())
        if not m:
            raise AbiError("cannot parse: %r" % line)
        slot, name, since, doc = m.groups()
        slots.append({
            "slot": int(slot),
            "name": name,
            "since": int(since),
            "doc": doc.strip(),
            "section": section or "",
        })
    if version is None:
        raise AbiError("no `version =` line")
    if not slots:
        raise AbiError("no slots")

    # Append-only, in order, no gaps: the slot number IS the address, so
    # a gap would silently shift every call after it.
    for i, s in enumerate(slots):
        if s["slot"] != i:
            raise AbiError("slot %d is in position %d -- slots are "
                           "append-only and may not be reordered or "
                           "renumbered" % (s["slot"], i))
        if s["since"] > version:
            raise AbiError("%s says since=%d but the ABI is version %d"
                           % (s["name"], s["since"], version))
    names = [s["name"] for s in slots]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        raise AbiError("duplicate names: %s" % ", ".join(sorted(dupes)))
    return version, slots


# --- the kernel's side ------------------------------------------------
def gen_jumptab(version, slots, impls):
    L = []
    L.append("; ca65 -- GENERATED by abi/gen_bindings.py. Do not edit.")
    L.append("; =====================================================================")
    L.append("; CXGEOS :: kernel/resident/jumptab.asm -- the ABI")
    L.append("; =====================================================================")
    L.append("; Every app reaches the kernel through here and nowhere else. The")
    L.append("; address of each JMP is fixed forever: slot n is at $%04X + n*3."
             % TABLE_ADDR)
    L.append(";")
    L.append("; Edit abi/cxgeos.abi and regenerate.")
    L.append("; =====================================================================")
    L.append("")
    L.append("; pushseg/popseg so including this cannot change the caller's")
    L.append("; segment. Without them everything after the include lands in")
    L.append("; JUMPTAB, and ld65 reports it as the table overflowing --")
    L.append("; which is a long way from what actually went wrong.")
    L.append(".pushseg")
    L.append('.segment "JUMPHDR"')
    L.append("cx_hdr_magic")
    L.append('    .byte "%s"                  ; the loader looks for this' % MAGIC)
    L.append("cx_hdr_version")
    L.append("    .word %d                    ; ABI version" % version)
    L.append("cx_hdr_slots")
    L.append("    .word %d                    ; slots" % len(slots))
    L.append("cx_hdr_init")
    L.append("    .word cx_init               ; the loader starts here")
    L.append("    .res 6, 0                   ; reserved")
    L.append("")
    L.append('.segment "JUMPTAB"')
    L.append("cx_jumptab")
    section = None
    for s in slots:
        if s["section"] != section:
            section = s["section"]
            L.append("")
            L.append("; --- %s %s" % (section, "-" * max(0, 60 - len(section))))
        impl = impls.get(s["name"])
        L.append("    jmp %-16s ; %2d  %s" % (impl, s["slot"], s["doc"]))
    L.append("")
    L.append(".popseg")
    L.append("")
    return "\n".join(L) + "\n"


# --- the app's side ---------------------------------------------------
def addr(slot):
    return TABLE_ADDR + slot * 3


ASM_SYNTAX = {
    #            comment  equate                     header
    "acme":     (";",     "{name} = ${addr:04X}",    ";ACME"),
    "ca65":     (";",     "{name} = ${addr:04X}",    "; ca65"),
    "64tass":   (";",     "{name} = ${addr:04X}",    "; 64tass"),
    "kick":     ("//",    ".label {name} = ${addr:04X}", "// KickAssembler"),
    "dasm":     (";",     "{name} = ${addr:04X}",    "; dasm"),
    "mads":     (";",     "{name} = ${addr:04X}",    "; MADS"),
    "vasm":     (";",     "{name} = ${addr:04X}",    "; vasm oldstyle"),
}


def gen_inc(dialect, version, slots):
    com, equ, head = ASM_SYNTAX[dialect]
    L = [head + " -- GENERATED by abi/gen_bindings.py. Do not edit."]
    L.append(com + " =====================================================================")
    L.append(com + " CXGEOS ABI version %d -- %d slots" % (version, len(slots)))
    L.append(com + " =====================================================================")
    L.append(com + " Call the kernel through these. They are addresses, not code: this")
    L.append(com + " file adds nothing to your program and links nothing in.")
    L.append(com + "")
    L.append(com + " Arguments go in the library's parameter block, X16_P0..P7 at $22,")
    L.append(com + " exactly as x16lib passes them -- an app that already uses x16lib")
    L.append(com + " uses the same names.")
    L.append(com + " =====================================================================")
    L.append("")
    L.append(equ.format(name="CX_ABI_VERSION", addr=version))
    L.append(com + "     the version these bindings were cut from; the kernel")
    L.append(com + "     reports its own through cx_version")
    L.append("")
    section = None
    for s in slots:
        if s["section"] != section:
            section = s["section"]
            L.append("")
            L.append("%s --- %s" % (com, section))
        L.append(equ.format(name=s["name"], addr=addr(s["slot"])))
        L.append("%s     %s" % (com, s["doc"]))
    L.append("")
    return "\n".join(L) + "\n"


def gen_h(compiler, version, slots):
    L = ["/* GENERATED by abi/gen_bindings.py. Do not edit. */"]
    L.append("/* =====================================================================")
    L.append(" * CXGEOS ABI version %d -- %d slots" % (version, len(slots)))
    L.append(" * =====================================================================")
    L.append(" * Call the kernel through these addresses. This header links nothing:")
    L.append(" * the kernel is already in memory when your app runs.")
    L.append(" *")
    L.append(" * CXGEOS passes arguments in the parameter block at $22 -- X16_P0..P7,")
    L.append(" * the same block x16lib uses -- because the kernel is assembly and a")
    L.append(" * fixed block is the one convention all five C compilers can agree on.")
    L.append(" * Set cx_p[] and call the slot:")
    L.append(" *")
    # no /* ... */ inside this block comment: the inner close would end
    # it early and spill the rest of the intro into the program
    L.append(" *     cx_p[0] = 100; cx_p[1] = 0;      -- x = 100")
    L.append(" *     cx_p[2] = 50;  cx_p[3] = 0;      -- y = 50")
    if compiler == "llvm":
        L.append(" *     cx_call_a(CX_GFX_PSET, 3);       -- colour 3")
        L.append(" *")
        L.append(" * On THIS compiler, cx_p is not the block itself. llvm-mos keeps its")
        L.append(" * soft stack pointer (__rc0/__rc1) and two reserved registers at")
        L.append(" * $22-$25 -- the same bytes as the kernel's block -- so a C write to")
        L.append(" * $22 corrupts the compiler's own stack. cx_p here is a mirror in")
        L.append(" * ordinary memory, and cx_run() carries it across the real block,")
        L.append(" * saving $22-$25 around the call. The mirror also carries what a")
        L.append(" * 6502 call has that C cannot see: cx_a/cx_x/cx_y go in; cx_a, cx_x")
        L.append(" * and cx_c -- the carry -- come back, so cx_ev_get can be judged.")
        L.append(" *")
        L.append(" * Build with -mreserve-zp=90: clang's whole-program pass otherwise")
        L.append(" * claims zero page from $26 up for hot statics, and everything from")
        L.append(" * $26 to $7F belongs to the kernel or to the app ZP convention.")
    else:
        L.append(" *     cx_call(CX_DIRTY_ADD);           -- args all in cx_p")
        L.append(" *")
        L.append(" * Only the bare cx_call is defined here so far: slots that take a")
        L.append(" * byte in A or a pointer in A/X need this compiler's own argument")
        L.append(" * conventions honoured, and a guessed macro that quietly puts the")
        L.append(" * byte in the wrong place is worse than none. The llvm header shows")
        L.append(" * the finished shape; x16_clib's ABI table is the reference for the")
        L.append(" * conventions. The helpers land per compiler, tested, with the SDK")
        L.append(" * packaging phase.")
    L.append(" * ===================================================================== */")
    L.append("")
    L.append("#ifndef CXGEOS_H")
    L.append("#define CXGEOS_H")
    L.append("")
    L.append("#define CX_ABI_VERSION  %d" % version)
    L.append("#define CX_ABI_SLOTS    %d" % len(slots))
    L.append("")
    if compiler == "llvm":
        L.append("/* the parameter block's mirror -- see the note above; the real block")
        L.append(" * at $22 is touched only inside cx_run(). Weak, so every translation")
        L.append(" * unit shares one copy under one unmangled name the asm can see. */")
        L.append("/* `used` keeps LTO from discarding what only the asm reads */")
        L.append("__attribute__((weak, used)) volatile unsigned char cx_p[8];")
        L.append("__attribute__((weak, used)) volatile unsigned char cx_a, cx_x, cx_y, cx_c;")
        L.append("__attribute__((weak, used)) volatile unsigned int  cx_slot;")
        L.append("")
        L.append("/* The C soft stack: the cx16 target pins __stack at $9F00, growing")
        L.append(" * DOWN through the kernel's graphics port ($9600-$9EFF) -- a mode")
        L.append(" * switch copies an engine image straight over the app's live stack")
        L.append(" * frames. An app owns $0801-$7FFF and nothing above it, so this")
        L.append(" * constructor moves the stack pointer to $8000 before main runs")
        L.append(" * (constructors execute from crt0 with no soft-stack frame live, so")
        L.append(" * the move is safe). The link script's plain assignment cannot be")
        L.append(" * --defsym'd away, hence runtime. */")
        L.append("__attribute__((weak, constructor)) void cx__stack_home(void) {")
        L.append('    asm volatile("stz 0x22\\n\\tlda #0x80\\n\\tsta 0x23" ::: "a", "memory");')
        L.append("}")
    else:
        L.append("/* the parameter block: X16_P0..P7 */")
        L.append("#define cx_p            ((volatile unsigned char *)0x0022)")
    L.append("")
    section = None
    for s in slots:
        if s["section"] != section:
            section = s["section"]
            L.append("")
            L.append("/* --- %s --- */" % section)
        L.append("#define %-18s 0x%04X   /* %s */"
                 % (s["name"].upper(), addr(s["slot"]), s["doc"]))
    L.append("")
    if compiler == "llvm":
        L.append("/* The crossing itself. The slot address is parked in __rc2/3 before")
        L.append(" * anything moves; $22-$25 ride the hardware stack -- and so does the")
        L.append(" * compiler's whole imaginary-register file at $02-$21: clang keeps")
        L.append(" * live values there across this call (its clobber list cannot say")
        L.append(" * otherwise for zero page), while any slot that reaches the KERNAL --")
        L.append(" * the text mode, the loaders, the DOS glue -- scribbles that range as")
        L.append(" * the KERNAL's own r0-r15. One string pointer held in __rc6/7 across")
        L.append(" * a cx_say was enough to print garbage; now the crossing preserves")
        L.append(" * the lot, exactly as the kernel's event IRQ does around itself. The")
        L.append(" * mirror is copied in, A/X/Y loaded, the slot called through a")
        L.append(" * trampoline, and registers, carry and the block all copied back. */")
        L.append("__attribute__((weak, noinline)) void cx_run(void) {")
        L.append("    asm volatile(")
        L.append('        "lda cx_slot\\n\\t"')
        L.append('        "sta __rc2\\n\\t"')
        L.append('        "lda cx_slot+1\\n\\t"')
        L.append('        "sta __rc3\\n\\t"')
        L.append('        "lda 0x22\\n\\tpha\\n\\t"')
        L.append('        "lda 0x23\\n\\tpha\\n\\t"')
        L.append('        "lda 0x24\\n\\tpha\\n\\t"')
        L.append('        "lda 0x25\\n\\tpha\\n\\t"')
        L.append('        "ldy #0x1f\\n\\t"')
        L.append('        "5:\\n\\t"')
        L.append('        "lda 0x02,y\\n\\t"')
        L.append('        "pha\\n\\t"')
        L.append('        "dey\\n\\t"')
        L.append('        "bpl 5b\\n\\t"')
        L.append('        "ldy #7\\n\\t"')
        L.append('        "1:\\n\\t"')
        L.append('        "lda cx_p,y\\n\\t"')
        L.append('        "sta 0x22,y\\n\\t"')
        L.append('        "dey\\n\\t"')
        L.append('        "bpl 1b\\n\\t"')
        L.append('        "ldy cx_y\\n\\t"')
        L.append('        "ldx cx_x\\n\\t"')
        L.append('        "lda cx_a\\n\\t"')
        L.append('        "jsr 2f\\n\\t"')
        L.append('        "sta cx_a\\n\\t"')
        L.append('        "stx cx_x\\n\\t"')
        L.append('        "php\\n\\t"')
        L.append('        "pla\\n\\t"')
        L.append('        "and #1\\n\\t"')
        L.append('        "sta cx_c\\n\\t"')
        L.append('        "ldy #7\\n\\t"')
        L.append('        "3:\\n\\t"')
        L.append('        "lda 0x22,y\\n\\t"')
        L.append('        "sta cx_p,y\\n\\t"')
        L.append('        "dey\\n\\t"')
        L.append('        "bpl 3b\\n\\t"')
        L.append('        "ldy #0\\n\\t"')
        L.append('        "6:\\n\\t"')
        L.append('        "pla\\n\\t"')
        L.append('        "sta 0x02,y\\n\\t"')
        L.append('        "iny\\n\\t"')
        L.append('        "cpy #0x20\\n\\t"')
        L.append('        "bne 6b\\n\\t"')
        L.append('        "pla\\n\\tsta 0x25\\n\\t"')
        L.append('        "pla\\n\\tsta 0x24\\n\\t"')
        L.append('        "pla\\n\\tsta 0x23\\n\\t"')
        L.append('        "pla\\n\\tsta 0x22\\n\\t"')
        L.append('        "bra 4f\\n\\t"')
        L.append('        "2:\\n\\t"')
        L.append('        "jmp (__rc2)\\n\\t"')
        L.append('        "4:"')
        L.append('        ::: "a", "x", "y", "cc", "memory");')
        L.append("}")
        L.append("")
        L.append("#define cx_call(slot)          (cx_slot = (slot), cx_run())")
        L.append("#define cx_call_a(slot, a)     (cx_a = (unsigned char)(a), cx_call(slot))")
        L.append("#define cx_call_ax(slot, a, x) (cx_a = (unsigned char)(a), cx_x = (unsigned char)(x), cx_call(slot))")
        L.append("#define cx_call_p(slot, ptr)   cx_call_ax((slot), ((unsigned int)(ptr)) & 0xFF, ((unsigned int)(ptr)) >> 8)")
        L.append("#define cx_ret(slot)           (cx_call(slot), cx_a)")
        L.append("#define cx_ret16(slot)         (cx_call(slot), (unsigned int)cx_a | ((unsigned int)cx_x << 8))")
    else:
        L.append("/* A bare call: every argument already sits in cx_p. */")
        L.append("#define cx_call(slot)      ((*(void (*)(void))(slot))())")
    L.append("")
    L.append("#endif /* CXGEOS_H */")
    return "\n".join(L) + "\n"


def find_impls(slots):
    """Map each ABI name to the kernel routine behind it.

    The manifest names the ABI; kernel/resident/impl.inc names the code.
    Keeping them apart is what lets a routine be renamed or replaced
    without touching a promise made to an app.
    """
    path = ROOT / "kernel" / "resident" / "impl.inc"
    if not path.exists():
        raise AbiError("%s is missing: it maps ABI names to kernel labels"
                       % path)
    impls = {}
    for line in path.read_text(encoding="ascii").splitlines():
        line = line.split(";")[0].strip()
        if not line:
            continue
        m = re.match(r"^(\w+)\s*=\s*(\w+)$", line)
        if not m:
            raise AbiError("cannot parse impl.inc: %r" % line)
        impls[m.group(1)] = m.group(2)
    missing = [s["name"] for s in slots if s["name"] not in impls]
    if missing:
        raise AbiError("impl.inc has no kernel routine for: %s"
                       % ", ".join(missing))
    extra = set(impls) - {s["name"] for s in slots}
    if extra:
        raise AbiError("impl.inc names slots the ABI does not have: %s"
                       % ", ".join(sorted(extra)))
    return impls


# --- self-tests -------------------------------------------------------
GOOD = """version = 2
#= system
0   cx_a   1   does a
1   cx_b   2   does b
"""


def selftest():
    fails = []

    def check(cond, what):
        print(("  ok   " if cond else "  FAIL ") + what)
        if not cond:
            fails.append(what)

    v, slots = parse(GOOD)
    check(v == 2 and len(slots) == 2, "parses version and slots")
    check(addr(0) == 0x8010 and addr(1) == 0x8013, "slot n is at $8010 + n*3")

    for bad, why in (
        ("version = 1\n#= s\n0 cx_a 1 x\n2 cx_b 1 y\n",
         "a gap in the slots is rejected"),
        ("version = 1\n#= s\n1 cx_a 1 x\n0 cx_b 1 y\n",
         "reordering the slots is rejected"),
        ("version = 1\n#= s\n0 cx_a 1 x\n1 cx_a 1 y\n",
         "a duplicate name is rejected"),
        ("version = 1\n#= s\n0 cx_a 9 x\n",
         "since above the ABI version is rejected"),
        ("#= s\n0 cx_a 1 x\n", "a missing version is rejected"),
    ):
        try:
            parse(bad)
            check(False, why)
        except AbiError:
            check(True, why)

    inc = gen_inc("ca65", *parse(GOOD))
    check("cx_a = $8010" in inc and "cx_b = $8013" in inc, "ca65 equates")
    kick = gen_inc("kick", *parse(GOOD))
    check(".label cx_a = $8010" in kick, "KickAssembler uses .label")
    h = gen_h("cc65", *parse(GOOD))
    check("#define CX_A               0x8010" in h, "C defines the address")
    check("CX_ABI_VERSION  2" in h, "C carries the version")

    print("selftest: %d failed" % len(fails))
    return 1 if fails else 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--check", action="store_true",
                    help="fail if anything would change (for CI)")
    args = ap.parse_args()

    if args.selftest:
        sys.exit(selftest())

    try:
        version, slots = parse(MANIFEST.read_text(encoding="ascii"))
        impls = find_impls(slots)
    except AbiError as e:
        sys.exit("abi: %s" % e)

    wrote = []

    def put(path, text):
        path.parent.mkdir(parents=True, exist_ok=True)
        old = path.read_text(encoding="ascii") if path.exists() else None
        if old == text:
            return False
        if args.check:
            sys.exit("%s is out of date -- run abi/gen_bindings.py" % path)
        path.write_text(text, encoding="ascii")
        wrote.append(path)
        return True

    put(ROOT / "kernel" / "resident" / "jumptab.asm",
        gen_jumptab(version, slots, impls))
    for d in ASM_DIALECTS:
        put(ROOT / "sdk" / ("include_" + d) / "cxgeos.inc",
            gen_inc(d, version, slots))
    for c in C_COMPILERS:
        put(ROOT / "sdk" / ("include_" + c) / "cxgeos.h",
            gen_h(c, version, slots))

    print("abi v%d: %d slots, $%04X..$%04X"
          % (version, len(slots), addr(0), addr(len(slots) - 1) + 2))
    if args.check:
        print("check: up to date")
    else:
        print("wrote %d file(s)" % len(wrote))


if __name__ == "__main__":
    main()
